### ISSUE TITLE
Can not go to next page

### ISSUE THREAD

**Issue by chengaomin** [naver/ngrinder#108]
![](http://i2.piimg.com/6c968b788c6bbb17.png)
I fork the last code,then building the new package for testing.
I can not go to next page where the list  is more then 10. 
Please fix it before release 3.4 version.Thanks.

**Comment by junoyoon** [comment]
which browser are you using?

**Comment by chengaomin** [comment]
@junoyoon I test it on 2 PC,using Chrome and IE11.
You haven't this problem using the latest code on your PC ?

**Comment by junoyoon** [comment]
@chengaomin No I didn't see the bug in my Mac. I'll  test it with PC.

**Comment by junoyoon** [comment]
@chengaomin I confirm the case. we'll fix it by 3.4

**Comment by junoyoon** [comment]
Fixed.

**Comment by chengaomin** [comment]
Thanks @junoyoon
