### ISSUE TITLE
intro.js needs Chinese translation

### ISSUE THREAD

**Issue by junoyoon** [naver/ngrinder#116]
We have integrated intro.js to have the ngrinder beginner to get familiar with ngrinder easily.
However we didn't translate it into Chinese yet.
We need help. 

https://github.com/naver/ngrinder/blob/12354470a32f14b6551dc6906cb010d62b69ee1d/ngrinder-controller/src/main/resources/messages_cn.properties#L428

@chengaomin Could you help us?

**Comment by chengaomin** [comment]
@junoyoon OK,I'll translate it,then pull the file.

**Comment by junoyoon** [comment]
@chengaomin Thanks!!! I'll wait for you.

**Comment by junoyoon** [comment]
Resolved by #123
