### ISSUE TITLE
New version of nGrinder

### ISSUE THREAD

**Issue by milkotodorov** [naver/ngrinder#122]
Hello,

as I can see there is no new version provided since 2014. Are there any plans for such? Will be the product further developed?

Regards,
Milko

**Comment by junoyoon** [comment]
We will release new version 3.4 next week
2016. 4. 26. 오전 7:36에 "Milko Todorov" <notifications@github.com>님이 작성:

**Comment by milkotodorov** [comment]
Thanks! Are there already a changelog?

**Comment by junoyoon** [comment]
No.. I didn't write it yet. But you can see them through
https://github.com/naver/ngrinder/milestones/3.4.0


2016-04-26 21:42 GMT+09:00 Milko Todorov <notifications@github.com>:

**Comment by junoyoon** [comment]
The release will be delayed to 3 weeks later.

**Comment by junoyoon** [comment]
It's released.
