### ISSUE TITLE
Change the ngrinder-recorder guide link

### ISSUE THREAD

**Issue by GwonGisoo** [naver/ngrinder#130]
#### AS-IS:
https://github.com/naver/ngrinder/tree/master/ngrinder-controller#ngrinder-recorder-chrome-extension
#### TO-BE:
https://github.com/naver/ngrinder/blob/master/ngrinder-recorder/README.md#ngrinder-recorder-chrome-extension

**Comment by junoyoon** [comment]
Fixed
