### ISSUE TITLE
Support CJK for folder and script name

### ISSUE THREAD

**Issue by chengaomin** [naver/ngrinder#134]
I find the url is wrong when I saved my script.
(my url contains Chinese)

`http://127.0.0.1:9000/script/detail/测试/pro/test.py`  to  `http://127.0.0.1:9000/script/list/??/pro/`

![](http://7xrn7f.com1.z0.glb.clouddn.com/16-5-3/65894915.jpg)

then

![](http://7xrn7f.com1.z0.glb.clouddn.com/16-5-3/82849542.jpg)

Can it support Chinese?

**Comment by junoyoon** [comment]
I have to know.. your env.
Did u run ngrinder on the tomcat or just run it by java -jar ngrinder.war way?

**Comment by chengaomin** [comment]
@junoyoon by java -jar

**Comment by junoyoon** [comment]
We found this happens when running ngrinder using embedded webserver or running it on old apache tomcat.

We can not fix this issue by 3.4.0 but will fix it by 3.4.1. Please run ngrinder on tomcat over 7.0.68 by then.

**Comment by junoyoon** [comment]
I've tried fix this just before. It's easily fixed than I though.

```
	return "redirect:/script/list/" + encodePathWithUTF8(basePath);
```

**Comment by junoyoon** [comment]
Fixed.
