### ISSUE TITLE
agent_monitor.conf配置文件描述有误

### ISSUE THREAD

**Issue by aizaimenghuangu** [naver/ngrinder#177]
ngrinder/ngrinder-controller/src/main/resources/ngrinder_agent_home_template/agent_monitor.conf
中描述的**monitor.binding_port=hostname_or_ip** 有误，修正为：monitor.binding_**ip**=hostname_or_ip

参考来源：
ngrinder/ngrinder-core/src/main/java/org/ngrinder/common/constants/MonitorConstants.java:
public interface MonitorConstants {
	**public static final String PROP_MONITOR_BINDING_IP = "monitor.binding_ip";**
	public static final String PROP_MONITOR_BINDING_PORT = "monitor.binding_port";

	/**
	 * Monitor Constant
	 */
	public static final int DEFAULT_MONITOR_COLLECTOR_INTERVAL = 1;
	public static final String DEFAULT_MONITOR_DOMAIN = "org.ngrinder.monitor";
	public static final String SYSTEM = "name=System";
	public static final String MONITOR_FILE_PREFIX = "monitor_system_";
}

**Comment by junoyoon** [comment]
FIXED. Thanks
