### ISSUE TITLE
How can we define many transactions in one script?

### ISSUE THREAD

**Issue by ke-liang** [naver/ngrinder#192]
Does NGrinder support many transactions in one script? it looks like NGrinder take one script as one transaction.
I want to define two transactions in my script, first is  get order list, and the second is get the order one by one based on the response of the first transaction(namely get order list), I involve this two transaction in one script, but unfortunately, it consider it as one transaction, I hope NGrinder can consider it as two transaction! how can I do it? thanks so much!

Anyway, I just want to analyze the result by transaction, transaction1 reach "xx" TPS, transaction2 reach "xx" TPS, Ngrinder support it?

**Comment by songeunwoo** [comment]
nGrinder good thing is the degree of freedom.
Way too often.
For example, one thing which story.
Not HTTPRequest, burning the @Test test methods

```java
@RunWith(GrinderRunner)
class TestRunner {
    static GTest test1
    static GTest test2
    @BeforeProcess
    public static void beforeProcess() {
        test1 = new GTest(1,"test1_statistics")
        test2 = new GTest(2,"test2_statistics")
        request1 = new HTTPRequest();
        HTTPPluginControl.getConnectionDefaults().timeout = 6000
        grinder.logger.info("before process.");
    }
 
    @BeforeThread
    public void beforeThread() {
        test1.record(this, "doTransaction1"); // Record current object’s doTransaction1 method into test1.
        test2.record(this, "doTransaction2"); // Record current object’s doTransaction2 method into test2.
        grinder.statistics.delayReports=true;
        grinder.logger.info("before thread.");
    }
 
    @Test
    public void doTransaction1(){
        // Do transactions here!!
    }
 
    @Test
    public void doTransaction2(){
        // Do another transactions here!!
    }
}
```
        
I hope a good test.

**Comment by ke-liang** [comment]
Do you have any example in Jypthon?

**Comment by songeunwoo** [comment]
i not have example. But I'll introduce me.
As it looks not difficult. 

http://grinder.sourceforge.net/g3/script-gallery.html

In a few days,
It plans to raise create a sample.
Good luck.

**Comment by ke-liang** [comment]
Thanks so much!
