### ISSUE TITLE
Can we post a request with JSON string in Groovy?

### ISSUE THREAD

**Issue by ke-liang** [naver/ngrinder#193]
It looks like request.post just support NVPair params to post request(application/x-www-form-urlencoded), if I want to post it with JSON string like below? how can I do it? can you help me? thanks in advance!
def jsonStr=
'''{ 
  "subject": "test subject", 
  "body": "test body", 
  "amount": "1", 
  "order_no": "ETyeh35145223663", 
  "channel": "upacp_pc_direct", 
  "currency": "cny", 
  "client_ip": "127.0.0.1", 
  "app": { 
    "id": "app_e9KKKC5uLSSKSuX1" 
  }, 
  "extra":{ 
    "result_url":"https://pingxx.com/?as=12|d=2" 
  }, 
  "time_expire":"", 
  "description": "test1description", 
  "metadata":[   
    {   
      "01":[1,2], 
      "02": "组的key和value的长度总和" 
    } 
  ] 
}'''

HTTPResponse result = request1.POST("/v1/create",jsonStr)

**Comment by ke-liang** [comment]
Yes, that's a good idea, but it looks like not work for me, what i want to know is how do prepare the params like below:
[
new NVPair("subject", "test subject"),
new NVPair("app", **[new NVPair("id", "app_e9KKKC5uLSSKSuX1")])**, //here need to contains another NVPair, how can i do it?
new NVPair("description", "test description")
] 

a field of NVPair need to contains a NVPair like below:
{
"app": { 
              "id": "app_e9KKKC5uLSSKSuX1" 
           }
}

Do you have some ideas? thanks very much!

**Comment by songeunwoo** [comment]
I think, How about converting parse the json a server-side coding?
I think a good argument to pass a java.lang.String value value.

http://grinder.sourceforge.net/g3/script-javadoc/HTTPClient/NVPair.html

**Comment by songeunwoo** [comment]
Well. It seems good.. 
However the data structure b/w json and url-form-encoded has different data stucture.. json can have nesting map but url-form-encoded type can not.
thank you.
