### ISSUE TITLE
Online editor replaces " with &quot; in scripts

### ISSUE THREAD

**Issue by milkotodorov** [naver/ngrinder#194]
Saving groovy scripts using the online editor is resulting in corrupt script, as it replaces the " characters with &quot. You cannot see this in the editor itself, but the script cannot be executed and downloading it and open it offline can shows that " are replaced by &quot.

**Comment by songeunwoo** [comment]
hi milkotodorov.
The issue has been corrected.
Soon after the deployment is expected in the near future.
You can check in below link.

https://github.com/naver/ngrinder/pull/190/files

thank you.

**Comment by milkotodorov** [comment]
hi,

I just tried your fix, but unfortunately it doesn't work. Still works as before.

Regards,
Milko

**Comment by songeunwoo** [comment]
hi,
The test results were good changes.
After clearing the existing source and 
Is it even the same newly created?

Is it possible to share your case?
Please reply.

**Comment by milkotodorov** [comment]
Hi,

I'm sorry, but I'm not quite sure whether I properly understand your question/request.
My case is quite simple - here is a bit more detailed description:

Let's say I'm creating a new groovy script called test_google.groovy that simply makes GET request to http://www.google.com:

![2016-09-05_11-01-10](https://cloud.githubusercontent.com/assets/14890886/18242856/a1f2b07a-7358-11e6-9586-be40449aab88.png)

However when you save this script with the nGrinder online editor and then try to download it and open it with some other editor offline it looks like this:

[test_google.groovy.txt](https://github.com/naver/ngrinder/files/454682/test_google.groovy.txt)

You will notice that everywhere in the script the " sign is replaced by &quot;
And of course this is causing an exception when you try to run any some tests using this script. I can only edit it offline and the online editor provided by the nGrinder is basically unusable. 

Regards,
Milko

**Comment by songeunwoo** [comment]
@milkotodorov Thanks! It's definately.. bug. We'll fix.
Thanks!

**Comment by songeunwoo** [comment]
@milkotodorov
Question
Can you give us a test environment?

**Comment by milkotodorov** [comment]
You can reproduce this on any PC. Just install the nGrinder even without any agent and try to use the online editor to edit some script. Then download it and there you go.

**Comment by songeunwoo** [comment]
@milkotodorov 
I have tried window, mac, linux.
Can you give more detail explaining?
For the operating system and version
And ngrinder version.
thank you.

**Comment by milkotodorov** [comment]
Hi @songeunwoo,

so I tried it just on now AWS VM using ubuntu-trusty-14.04 image. Then I use JDK 1.8, Tomcat 8.5.5 and nGrinder 3.4. Can be reproduced in minutes.

Follow the following steps:

1. Create a VM on AWS with ubuntu-trusty-14.04 image (I believe that you can use 16 as well)
2. Download and extract JDK: wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz
3. Download and extract Tomcat8: http://mirror.dkd.de/apache/tomcat/tomcat-8/v8.5.5/bin/apache-tomcat-8.5.5.tar.gz
4. Install the nGrinder 3.4 and try to create and edit a simple script.
5. Download it to your PC and open it with a standalone editor (Notepad or whatever)

Hope this helps.

Regards,
Milko

**Comment by songeunwoo** [comment]
@milkotodorov 
Would you feedback after the test?

**Comment by milkotodorov** [comment]
Hi @songeunwoo,

perhaps I won't have the chance this week to do it, but I'll try next.

Regards,
Milko

**Comment by songeunwoo** [comment]
Hi @milkotodorov 

This commit is referred to as defense look for logic in your case.
Because I did not reproduce your case.
It has prepared a download link for easy testing.
https://drive.google.com/open?id=0B-2ubXuQYbbSZU90aGQ0YmVPZW8

```
install jdk and try

java -jar ngrinder-controller-3.4.1-SNAPSHOT.war
```

thank you.

**Comment by milkotodorov** [comment]
I see int his commits that you are replacing the &quot with ", right? However it shouldn't be the case - the text should come in the right format so you do not need to do "replaceAll", don't you think so?

**Comment by rxy007** [comment]
I also encountered similar problems, is the problem solved?

**Comment by milkotodorov** [comment]
hi @songeunwoo,

I just verified your fix and it is unfortunately not working. However without you being able to reproduce it it would be more difficult for you to fix it. What's the problem with reproducing it? I've wrote you the steps a few replies earlier in the thread.

Regards,
Milko

**Comment by lunker** [comment]
같은 문제 발생하였습니다.

**Comment by milkotodorov** [comment]
Hi, did you manage to reproduce it?
@lunker you may want to help @songeunwoo to reproduce the issue

**Comment by rxy007** [comment]
Sorry! Behind me to avoid the use online editor.


rxy1234567890@163.com
 
From: Milko Todorov
Date: 2016-10-24 15:56
To: naver/ngrinder
CC: rxy007; Comment
Subject: Re: [naver/ngrinder] Online editor replaces " with &quot; in scripts (#194)
Hi, did you manage to reproduce it?
@lunker you may want to help @songeunwoo to reproduce the issue

**Comment by milkotodorov** [comment]
Sorry, I do not understand.

**Comment by Mavlarn** [comment]
I can reproduce this error. I downloaded the version of 3.4, the script can not be validated in editor. I tried the script created by quick test, which should be in SVN, and I also tested a new script. They both have same error.

After some investigation, I found:
 1. the content sent to server side is right. all `"` is just `"`, not encoded.
 2. the file in controller home dir, 'cat .ngrinder/script/admin/my_test.groovy ' is not right, all `"` are encoded with `&quot;`.

So, the problem maybe in file copy/save file process. which is in ScriptValidationService.validate(...):
```
			if (useScriptInSVN) {
				fileEntryService.writeContentTo(user, scriptEntry.getPath(), scriptDirectory);
			} else {
				FileUtils.writeStringToFile(scriptFile, scriptEntry.getContent(),
						StringUtils.defaultIfBlank(scriptEntry.getEncoding(), "UTF-8"));
			}
```

I hope this can help.

**Comment by Mavlarn** [comment]
And, even if I modify a existing script, and then run the test, there will be the error as above.

**Comment by milkotodorov** [comment]
Precisely. Any script edited with this online editor cannot be used later on.

**Comment by rxy007** [comment]
yes,do not use online editor!



rxy1234567890@163.com
 
From: Mavlarn
Date: 2016-10-27 16:58
To: naver/ngrinder
CC: rxy007; Comment
Subject: Re: [naver/ngrinder] Online editor replaces " with &quot; in scripts (#194)
And, even if I modify a existing script, and then run the test, there will be the error as above.

**Comment by milkotodorov** [comment]
Any update here?

**Comment by hugo-paredes** [comment]
I've the same issue as you @milkotodorov. I'm also using version 3.4 on a machine with Windows 10 and running the app in Tomcat 9.
If I try to validate any Jython script, it gives me the same error as you. But, if I run the generated script using the google.com example, it works. If I put the URL I want to actually test, it throws an exception complaining about the &quot; in the script.
It even fails when I put the script that I successfully run manually on Grinder.

No news here?

**Comment by leehowon** [comment]
이거 해결 됐나요..?

**Comment by milkotodorov** [comment]
No - it is not solved yet. And no answer still.

**Comment by milkotodorov** [comment]
@songeunwoo, do you still have issues reproducing this issue? Any updates?

**Comment by songeunwoo** [comment]
@milkotodorov 
hi. It is hard to reproduce. 
I do not know what environment it is reproduced.
We are still looking for a solution.

**Comment by lopiter** [comment]
hi , if there is not security issue
can you share your .ngrinder directory
??(this directory is in your homedirectory)

**Comment by milkotodorov** [comment]
Man, so many people already reproduced this and I wrote you step by step how to do it too. What more I can do to help you?

**Comment by leehowon** [comment]
우리가 도울 일이 있을까요?

**Comment by lopiter** [comment]
we fixed this issue.
please download new version 3.4.1(https://github.com/naver/ngrinder/releases) and test
thank you

**Comment by milkotodorov** [comment]
Thanks!

**Comment by leehowon** [comment]
아주 잘 되네요.. 감사합니다

**Comment by lopiter** [comment]
w==

**Comment by khchcker** [comment]
i also  encounter this problem ,The script in editor is correct , 
when verify the script ,  report a bug.  the script file on server is wrong..
![image](https://user-images.githubusercontent.com/16751397/55868922-06573780-5bb8-11e9-86a4-e4d200eb555d.png)

**Comment by genieCS** [comment]
I also have same issue. When I edit and save scripts using online editor, quotes are replaced.
I am using 3.4.2 on Mac.

저도 온라인에서 스크립트 저장시 스크립트 에러가 뜹니다. 저는 3.4.2 버전 쓰고 있어요
