### ISSUE TITLE
Can we limit QPS in ngrinder?

### ISSUE THREAD

**Issue by aqie4203** [naver/ngrinder#197]
I know we can control QPS by limit processes and threads, but additional qps limit is also useful in perf test. Is there a easy way to implement it.

**Comment by songeunwoo** [comment]
Please explain. what QPS?
QPS == TPS ..?

**Comment by aqie4203** [comment]
QPS == TPS :(

**Comment by songeunwoo** [comment]
we already implied feature that you ask me.
![1473046567234](https://cloud.githubusercontent.com/assets/16470009/18236823/6215bfd0-7365-11e6-8cd4-77447025fef9.jpg)

You can comfortably use.

**Comment by junoyoon** [comment]
No.. there is no support for QPS in ngrinder.
usually.. people limits QPS by add sleep time but as you may think, it's not accurate.
