### ISSUE TITLE
Get TPS Statistics in Script

### ISSUE THREAD

**Issue by SimpleGitA** [naver/ngrinder#199]
According the Statistics document.
http://grinder.sourceforge.net/g3/script-javadoc/net/grinder/script/Statistics.html
We can get peakTPS as
grinder.getStatistics().getDouble("peakTPS")
But I got error bellow
![image](https://cloud.githubusercontent.com/assets/21999428/18240131/776d8324-737c-11e6-8ec0-63ee8cc9c428.png)
So question is: Is there any way we can get TPS in Jpython script?

**Comment by songeunwoo** [comment]
hi,
when peakTPS call time differences.
please post your script.

**Comment by SimpleGitA** [comment]
I tried below, but TPS always return 0.
grinder.logger.info("Peak TPS for Current is %f" %grinder.getStatistics().getForCurrentTest().getDouble("peakTPS"))
			grinder.logger.info("Peak TPS for Last is %f" %grinder.getStatistics().getForLastTest().getDouble("peakTPS"))

**Comment by aqie4203** [comment]
Hi songeunwoo, do we have way to get TPS in script?

**Comment by junoyoon** [comment]
Hi. All. I think @songeunwoo is wrong answer..
There is no way to get the peekTPS in the test code itself.

http://grinder.sourceforge.net/g3/script-javadoc/net/grinder/script/Statistics.html
```
untimedTests	basic long	Not relevant.
period	basic long	Not relevant.
peakTPS	basic double	Not relevant.
```

The document above is used to define custom statistic... See.
http://www.cubrid.org/wiki_ngrinder/entry/user-defined-statistic-in-ngrinder
