### ISSUE TITLE
http post data 관련 

### ISSUE THREAD

**Issue by lunker** [naver/ngrinder#216]
안녕하세요. 
groovy script로 http post test case 작성중입니다.
server는 Spring이며, 
acccept : application/json, content-type application/json 입니다.(requestbody, response body annotation사용중) 

현재 문제상황은

HttpRequest의 data관련 method중에서 formdata외에는 setData()뿐입니다.
- JSONObject 객체를 byte[] 변환 
- NVPair[] -> byte[] 변환

두 방법으로 setdata()를  사용해 보았지만 http 400 error를 뱉습니다. 

현재 ngrinder에서 어떤 방법으로 해결 가능한지 궁금합니다.

**Comment by junoyoon** [comment]
어떻게 스크립트를 작성하셨었는지 올려주시겠나요?

**Comment by lunker** [comment]
1) nvpair[]로 전송한 케이스 
(값은 임의로 변경하였습니다)
request.POST(url,
		[new NVPair("test1","1"), new NVPair("test2","test"), new NVPair("test3","test3")] as NVPair[])





2) byte[]로 전송한 케이스. 아래의 코드를 사용하여 object to byte[]로 변환하였습니다.

byte[] bytes
ByteArrayOutputStream bos = new ByteArrayOutputStream();
ObjectOutput out = null;
try {
  out = new ObjectOutputStream(bos);   
  out.writeObject(data.toString());
  out.flush();
  bytes = bos.toByteArray();
} finally {
  try {
	bos.close();
  } catch (IOException ex) {
	// ignore close exception
  }
}
byte[]로 전송한 경우는 위의 코드에 NVPair[]를 byte[]로 변환하였고, 
JSONObject는 아래와 같이 생성 후 jsonDataStr를 byte[]로 변환하여 전송하였습니다.
JSONObject testJson= new JSONObject()
testJson.put("test1","1")
testJson.put("test2","test")
testJson.put("test3","test")
String jsonDataStr = testJson.toString()

**Comment by songeunwoo** [comment]
@lunker 안녕하세요.
작성 해주신 코드에서 크게 이상함 점이 보이진 않는거 같아요.
작성하신 전체 소스를 올려 주시면 확인하는데 도움이 될거 같은데 올려 주실수 있나요?

**Comment by junoyoon** [comment]
json을 보내는 부분에서는 큰 문제가 없어 보이지만..
NVPair는 Groovy 객체를 바로 바이트로 보내면 Web에서 처리할 수 없습니다.
```
NVPair[] form_data = { new NVPair("option", "doit") };
byte[] data = Codecs.nv2query(form_data).getByte();
```

위와 같이 하셔야 합니다.
