### ISSUE TITLE
Importing SSL module into nGrinder

### ISSUE THREAD

**Issue by InH4te** [naver/ngrinder#217]
In Jython, I'm trying to use 

`import ssl`

But am getting a "no module named ssl" error. So, have created a separate lib folder containing the ssl.py library. But ssl.py requires many dependencies and one of them is the _jythonlib which we can't upload into nGrinder.

How can we import the ssl module in nGrinder?

**Comment by junoyoon** [comment]
I highly recommend u to use groovy. because it uses jython, module which involves native call is not imported well.
