### ISSUE TITLE
Send JSON body in a PUT request using nGrinder's Groovy APIs.

### ISSUE THREAD

**Issue by rachitchauhan43** [naver/ngrinder#221]
Hi Team

I am usgin groovy to write nGrinder script. 
My APIS accept JSON payload as request body and the available options for PUT call, as mentioned in official doument, are : 

```
1. PUT(java.lang.String uri) 
2. PUT(java.lang.String uri, byte[] data) 
3. PUT(java.lang.String uri, byte[] data, NVPair[] headers) 
4. PUT(java.lang.String uri, java.io.InputStream inputStream) 
5. PUT(java.lang.String uri, java.io.InputStream inputStream, NVPair[] headers)
```

Resource: http://grinder.sourceforge.net/g3/script-javadoc/net/grinder/plugin/http/HTTPRequest.html  

As you can see that, there is no method accepting either JSONObject or String as a request body.Only 
ByteArray and InputStreams are the valid ones. 

So how to make a PUT call for an API with JSON as a request body ?

**Comment by GwonGisoo** [comment]
Use code below:
```
def reqBody = "{id:'123',value:123}";
request.POST("http://you_api_url", reqBody.getBytes())
```

**Comment by rachit1010** [comment]
Hi GwonGisoo 

I tried out the approach you mentioned.
But it gives a "400" error from my APIS side saying Bad Request since my APIs doesn't accept bytes as request body.
```
HTTPResponse result=requestDummy.PUT(url,reqBody.getBytes(),headers as NVPair[])
```

**Comment by GwonGisoo** [comment]
Please change to HTTP post method instead PUT?

**Comment by rachit1010** [comment]
Hi GwonGisoo

My API is a HTTP PUT call, if i try to hit that endpoint with HTTP POST method then my app gives,and should give, error saying "405:Method not allowed".
I can't change the protocols my APIS are working upon.

**Comment by zero5two4** [comment]
Hello.
I got a same situation '405:Method not allowed"
I tried PUT or POST Method on URL of web-browser, and it didn't work.
But I tried methods on postman then it works!

**Comment by junoyoon** [comment]
Do not post any question here. [Use discussion](https://github.com/naver/ngrinder/discussions)
