### ISSUE TITLE
Updates in resources in Groovy Maven project are not transferred to Agent

### ISSUE THREAD

**Issue by tolis-e** [naver/ngrinder#232]
Hello,

I have a Groovy Maven project which has a resources folder. Inside the resources folder there is a properties file. I update the properties file and commit it on SVN. Although, the agent still receives the old version of the properties file. Would you please tell how to make my agent to always get the fresh files from the repository? I have tried the system.conf properties without luck. At the current moment I'm investigating whether the issue is related to EHCache.

Thanks,
Tolis

**Comment by songeunwoo** [comment]
Hello,
It has nothing to do with EHCache.
The agent is always supposed to receive new resources every time the test is run.
Try saving the test file again, 
It may be necessary to check the resources downloaded by the agent.
See the figure below for confirmation.

![2017-03-09 10 45 08](https://cloud.githubusercontent.com/assets/16470009/23732335/ee4cd7b8-04b5-11e7-91b3-7abebc0ae414.png)
![2017-03-09 10 44 53](https://cloud.githubusercontent.com/assets/16470009/23732337/ef8ecf3c-04b5-11e7-9ef6-70a0ca6cdfb1.png)

If you are using the latest version of ngrinder, I think agent restart seems to be good.

**Comment by tolis-e** [comment]
@songeunwoo Thank you for your answer.

The test file (MyTest.groovy) is always updated on the Agent. The myproject/**resources/conf/my.properties** of my Groovy Maven project is not updated.

I have tried everything. Installed NGrinder 3.3, installed NGrinder 3.4.1, deleted the SVN repository and created a new one with different name. Still I get a cached old version of my resources folder.

**Comment by tolis-e** [comment]
I found the root cause. NGrinder works correctly. 

Thank you @songeunwoo and team for the great product :)
