### ISSUE TITLE
i have doubt,why in my out.csv ,all of the columns are "0",It happens every now and then

### ISSUE THREAD

**Issue by xiaoyi8837** [naver/ngrinder#244]
![image](https://cloud.githubusercontent.com/assets/20347806/26778666/caf2e5d8-4a14-11e7-87bf-467122585708.png)

here they are,
If the connection fails, the case should be counted in the error column, but the total number of errors in the test is 0

**Comment by Mavlarn** [comment]
How did you check result in your test script? Maybe you skip the test for error, because your test count is 0.

**Comment by xiaoyi8837** [comment]
Thanks, I will ckeck my script again
