### ISSUE TITLE
/wiki/Groovy-Maven-Structure- ngrinder-groovy version miss.

### ISSUE THREAD

**Issue by kingbbode** [naver/ngrinder#276]
https://github.com/naver/ngrinder/wiki/Groovy-Maven-Structure

The generated pom.xml is ngrinder-groovy version 3.4, 

but version 3.4 does not exist in 'https://github.com/naver/nhnopensource.maven.repo/tree/master/releases/org/ngrinder/ngrinder-groovy' .

**Comment by genieCS** [comment]
friendly nudge to check this issue.

**Comment by junoyoon** [comment]
@donggyu04  check this.

**Comment by junoyoon** [comment]
We are using the maven repo in the following location. 
Please check the generated pom.xml

```
	<repositories>
		<repository>
			<id>ngrinder.maven.repo</id>
			<url>https://github.com/naver/ngrinder/raw/ngrinder.maven.repo/releases</url>
		</repository>
	</repositories>
```

**Comment by donggyu04** [comment]
Yes,  we move maven repository url to https://github.com/naver/ngrinder/raw/ngrinder.maven.repo/releases

```
    repositories {
        maven { url "https://github.com/naver/ngrinder/raw/ngrinder.maven.repo/releases" }
    }

    compile('org.ngrinder:ngrinder-groovy:3.4.2')
```
![image](https://user-images.githubusercontent.com/14273601/59666028-fcbd0200-91ee-11e9-84d7-0aaa216e16cc.png)
