### ISSUE TITLE
ngrinder 를 ncloud 에 설치 후, 타 서버로 부하를 줄 경우, agent 를 늘려도 부하량이 증가하지 않습니다.

### ISSUE THREAD

**Issue by tius1234** [naver/ngrinder#283]
안녕하세요.

대부분 영어로 이슈를 적으셔서 한글로 적기가 조금 뻘쭘하네요 ^^;

이번에 저희가 nGrinder 를 ncloud VM 에 설치 후, 외부 서버로 부하테스트를 진행하고 있습니다.

그런데, nGrinder 가 설치된 Agent(VM) 숫자를 늘려도 TPS 및 총실행테스트 수치의 변화가 거의 없어 문의 드립니다. 

우선 컨트롤러의 경우, 3.4.1 버전의 war 파일을 구동 시키는 경우와 3.4 버전의 docker 를 실행시키는 경우로 테스트 했습니다. (그런데 둘다 별 차이는 없었습니다.)

docker 실행 명령어 : docker run -d -v ~/package/ngrinder-controller:/opt/ngrinder-controller -p 80:80 -p 16001:16001 -p 12000-12009:12000-12009 ngrinder/controller:3.4

war 실행 명령어 : java -XX:MaxPermSize=2048m -jar ngrinder-controller-3.4.1.war --port 80

controller 및 agent VM 스펙은 CentOS 7 / 4vCPU / 8G 장비로 테스트 하였습니다.

처음에는 저희 서비스를 직접 호출 하는 형태로 테스트 하다가, 뭔가 이상한듯 하여
nginx 기본 설치 후, index.html 을 호출하는 것으로 변경하여 테스트를 하였습니다.

[ncloud -> 외부] 
ncloud 5대 Agent(VM) 에서 외부 호출. (LBS -> 목적지 서버 2대)
ncloud 5대 Agent(VM) 에서 외부 호출. (LBS -> 목적지 서버 5대 로 증설) 
ncloud 10대 Agent(VM) 에서 외부 호출. (LBS -> 목적지 서버 5대) 

관련해서, ngrinder 설정의 경우, 기본 셋팅으로 진행을 하였습니다. 

위와 같이 agent 를 늘렸는데도, TPS 가 약 4000 정도에서 더 늘어나지를 않는데, 뭔가 제가 더 확인해 볼 것들이 있을까요? vUser 는 4500 명으로 테스트를 진행했습니다. (조금 씩 늘려도 보고 줄여도 봤는데, 수치상 큰 변화는 없었습니다.)

테스트 결과 이미지와 로그 파일 일부를 첨부 합니다.

[ngrinder011-0.log](https://github.com/naver/ngrinder/files/1905588/ngrinder011-0.log)

![ncloud](https://user-images.githubusercontent.com/11863150/38713578-c642477a-3f0c-11e8-957b-f7cd8e171f6a.png)

**Comment by junoyoon** [comment]
너무 오래된 이슈라 닫습니다.
