### ISSUE TITLE
nGrinder region 

### ISSUE THREAD

**Issue by umyonghyun** [naver/ngrinder#290]
사용자(본인)은 한국에 있지만 외국에 있는 웹페이지에도 과부하를 줄수 있는 방법이 있는지 궁금합니다.

**Comment by lopiter** [comment]
지역에 대한 특별한 제한은 없는것으로 알고 있습니다. 다만 한국에 에이전트를 설치하고 외국에 있는 페이지에 부하를 발생시키면 같은 지역에서 테스트하는것 보다는 성능이 좋지 않게 나올것 같습니다.

**Comment by umyonghyun** [comment]
그렇다면 외국 지역에 대해 에이젼트를 설치 할 수 있는 방법이 있습니까??

**Comment by lopiter** [comment]
@umyonghyun 테스트하시고 싶은 서버가 있는 지역에 ngrinder agent를 설치 할수 있는 서버를 준비하실수 있으면,
해당 서버에 agent를 설치하시면 될것 같습니다.
