### ISSUE TITLE
Can't use setLevel() to adjust the logger level

### ISSUE THREAD

**Issue by beyondht2003** [naver/ngrinder#300]
Do you need to adjust the logger level to only see the errors? Read followings.
https://github.com/naver/ngrinder/wiki/How-to-adjust-logger-level

I try to use LoggerFactory.getLogger("worker").setLevel(Level.ERROR) to adjust the logger level, but I found no such function in the interface "Logger" .

<img width="1064" alt="qqqqq" src="https://user-images.githubusercontent.com/9694790/43687320-8ab6ee14-9898-11e8-8de7-4698efa4e139.png">
<img width="683" alt="qqqqq1" src="https://user-images.githubusercontent.com/9694790/43687321-8b1e92ee-9898-11e8-9a51-aeb5959aa567.png">

**Comment by junoyoon** [comment]
You need cast getLogger result to ch.qos.logback.classic.Logger

**Comment by beyondht2003** [comment]
@junoyoon Thank U, ((ch.qos.logback.classic.Logger)LoggerFactory.getLogger("worker")).setLevel(Level.ERROR) , it works .
