### ISSUE TITLE
Provide agent management menu for user

### ISSUE THREAD

**Issue by donggyu04** [naver/ngrinder#304]
-  Provide UI that non-administration user see agent information(name, ip, etc..) from agent management menu.
 - Users can view only public agents.

**Comment by junoyoon** [comment]
* Show only following when user permission.
![image](https://user-images.githubusercontent.com/1000705/44072067-bad049d4-9fc7-11e8-96f9-3cbd9051480a.png)

**Comment by donggyu04** [comment]
finished by #317
