### ISSUE TITLE
Release 3.3.1 

### ISSUE THREAD

**Issue by junoyoon** [naver/ngrinder#35]
@newpcraft  @maoyubin @Mavlarn @Chojiwon 

I think we're almost ready to release 3.3.1 which includes. #32 #33 #34, #36 and http://jira.cubrid.org/browse/NGRINDER-725 fixes?
 
What do you think you guys? If you agree with this, please add the +1 comment (It's the very conventional way to get agreed.

If we all agree on this, we should do following as you guys know.

1. I have to move all 3.3.1-SNAPSHOT to 3.3.1 and tag the version.
2. @maoyubin deploys ngrinder 3.3.1 parent, core, runtime, groovy into maven repo.
3. @newpcraft deploys ngrinder 3.3.1 and JVM plugin into the internal instance(test) 
4. @Chojiwon does testing.
5. I or @newpcraft  writes the release note.
6. @newpcraft and I fix the bugs @Chojiwon  found
7. @Chojiwon deploys 3.3.1 into demo machine
8. @newpcraft deploys 3.3.1 into real machine.
9. I upload the binary into sourceforge.

**Comment by choihyunbin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

chlgusrla@naver.com 님께 보내신 메일 <Re: [ngrinder] Release 3.3.1 (#35)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
