### ISSUE TITLE
Bad Set-Cookie header when fetching X-CSRF-Token in headers

### ISSUE THREAD

**Issue by HelenMishra** [naver/ngrinder#352]
Hi,
We have a get request which fetches xcsrf token in response header .But when i run this request in nGrinder with groovy script, it fails with the below error.
2018-12-17 10:18:56,765 ERROR Bad Set-Cookie header: JSESSIONID=4E76D6A9FE09521A19F082EE1F6C093A; Path=/; Secure;, __VCAP_ID__=97f8b5cf-fd0b-4002-5939-731c; Path=/;, Secure
No '=' found for token starting at position 113
Can you please help?

Regards!
Helen

**Comment by junoyoon** [comment]
```
VCAP_ID=97f8b5cf-fd0b-4002-5939-731c; Path=/;, Secure
```
I think the server returns invalid cookie 
Especially the following part. comma after Path=/; should not be followed. 
Please ask your server developer.

Path=/;**,** Secure

**Comment by HelenMishra** [comment]
Hi junoyoon,
Thanks for your quick response.But the same request works perfectly fine when i fetch the csrf token using Post man client.Also works from Java program.So it can not be a server issue working differently for different clients.
