### ISSUE TITLE
ValidateScript error

### ISSUE THREAD

**Issue by keny16888** [naver/ngrinder#363]
Hello
      I use the 3.5.0 development version. It appears in ValidateScript. 3.4 Previous bug, prompt me ${NGRINDER_HOME}/ script/admin/TestRunner.groovy: 46: unexpected token: &amp; @ line 46, column 22.
Test = new GTest (1, &amp; quot; www.baidu.com")

Good luck
Thank you

**Comment by donggyu04** [comment]
@keny16888 

Refer to this https://github.com/naver/ngrinder/issues/389#issuecomment-501570407

**Comment by donggyu04** [comment]
refer to #389
