### ISSUE TITLE
How to fix problem: MultipleCompilationErrorsException: startup failed? thx

### ISSUE THREAD

**Issue by fengnex** [naver/ngrinder#386]
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/root/.ngrinder_agent/file-store/admin/current/qqcom.groovy: 46: unexpected token: & @ line 46, column 23.
                test = new GTest(1, &quot;www.qq.com&quot;)
                         ^

1 error

**Comment by fengnex** [comment]
The version is v3.4.2

**Comment by fengnex** [comment]
cat /etc/issue
CentOS release 6.7 (Final)
Kernel \r on an \m

**Comment by songeunwoo** [comment]
Can you see the tested groovy file?

**Comment by fengnex** [comment]
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/root/.ngrinder_agent/file-store/admin/current/qqcom.groovy: 46: unexpected token: & @ line 46, column 23.
                test = new GTest(1, &quot;www.qq.com&quot;)
                         ^

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309) ~[groovy-all-2.2.1.jar:2.2.1]

**Comment by fengnex** [comment]
import static net.grinder.script.Grinder.grinder
import static org.junit.Assert.*
import static org.hamcrest.Matchers.*
import net.grinder.plugin.http.HTTPRequest
import net.grinder.plugin.http.HTTPPluginControl
import net.grinder.script.GTest
import net.grinder.script.Grinder
import net.grinder.scriptengine.groovy.junit.GrinderRunner
import net.grinder.scriptengine.groovy.junit.annotation.BeforeProcess
import net.grinder.scriptengine.groovy.junit.annotation.BeforeThread
// import static net.grinder.util.GrinderUtils.* // You can use this if you're using nGrinder after 3.2.3
import org.junit.Before
import org.junit.BeforeClass
import org.junit.Test
import org.junit.runner.RunWith

import java.util.Date
import java.util.List
import java.util.ArrayList

import HTTPClient.Cookie
import HTTPClient.CookieModule
import HTTPClient.HTTPResponse
import HTTPClient.NVPair

/**
 * A simple example using the HTTP plugin that shows the retrieval of a
 * single page via HTTP. 
 * 
 * This script is automatically generated by ngrinder.
 * 
 * @author admin
 */
@RunWith(GrinderRunner)
class TestRunner {

	public static GTest test
	public static HTTPRequest request
	public static NVPair[] headers = []
	public static NVPair[] params = []
	public static Cookie[] cookies = []

	@BeforeProcess
	public static void beforeProcess() {
		HTTPPluginControl.getConnectionDefaults().timeout = 6000
		test = new GTest(1, "www.qq.com")
		request = new HTTPRequest()
		grinder.logger.info("before process.");
	}

	@BeforeThread 
	public void beforeThread() {
		test.record(this, "test")
		grinder.statistics.delayReports=true;
		grinder.logger.info("before thread.");
	}
	
	@Before
	public void before() {
		request.setHeaders(headers)
		cookies.each { CookieModule.addCookie(it, HTTPPluginControl.getThreadHTTPClientContext()) }
		grinder.logger.info("before thread. init headers and cookies");
	}

	@Test
	public void test(){
		HTTPResponse result = request.GET("www.qq.com", params)

		if (result.statusCode == 301 || result.statusCode == 302) {
			grinder.logger.warn("Warning. The response may not be correct. The response code was {}.", result.statusCode); 
		} else {
			assertThat(result.statusCode, is(200));
		}
	}
}

**Comment by fengnex** [comment]
The above is its the whole auto-generated script code

**Comment by fengnex** [comment]
It can correctly run over on Windows 7

**Comment by fengnex** [comment]
Found that's because the character like " has been converted as &quot;, this should be the root cause.

Then what's the reason? How to fix it?

**Comment by songeunwoo** [comment]
I am using CentOS Linux release 7 (7.4.1708), but I have no problems.
I think it looks like an environmental problem. 
How about another version of CentOS?

**Comment by fengnex** [comment]
Found that the root cause lies in the Spring MVC related link, then I replace all "& quot ;", you know the it's the html expression of \", with \" in FileEntryController's save method, then it's OK now.

thank you @songeunwoo

**Comment by songeunwoo** [comment]
I am glad the issue has been resolved.
Have a nice day.
I will close the issue.

**Comment by bilal1102** [comment]
i have the same issue and try all above suggestions but its not fixed.
plz help me.

**Comment by donggyu04** [comment]
@bilal1102 

Hi, could you answer the questions?

1. What is your OS, ngrinder version?
2. Install 3.4.4 & Could you delete script and create a new one?
