### ISSUE TITLE
about groove Script Error 

### ISSUE THREAD

**Issue by jinnyum** [naver/ngrinder#387]
Running script validation immediately after creating the script will result in the following error
Why is that?

${NGRINDER_HOME}\script\admin\Test.groovy: 46: unexpected token: & @ line 46, column 23.
   		test = new GTest(1, &quot;www.daum.net&quot;)
                         ^

1 error

**Comment by donggyu04** [comment]
It's a similar issue to the #386 could you refer to this?

**Comment by jinnyum** [comment]
> It's a similar issue to the #386 could you refer to this?

I checked what you told me.
However, I don't know what to do.
The problem is still going on.
T_T

**Comment by donggyu04** [comment]
@jinnyum 
Check your context path is root. https://github.com/naver/ngrinder/issues/389#issuecomment-501570407

**Comment by donggyu04** [comment]
refer to #389
