### ISSUE TITLE
error package sun.net.spi.nameservice does not exist

### ISSUE THREAD

**Issue by jinnyum** [naver/ngrinder#388]
gradlew war command execute error...

How should I fix it?

> Task :ngrinder-runtime:compileJava FAILED
/home/ec2-user/ngrinder/ngrinder-runtime/src/main/java/org/ngrinder/dns/LocalManagedDnsDescriptor.java:25: error: package sun.net.spi.nameservice does not exist
public class LocalManagedDnsDescriptor implements sun.net.spi.nameservice.NameServiceDescriptor {
                                                                         ^
/home/ec2-user/ngrinder/ngrinder-runtime/src/main/java/org/ngrinder/dns/LocalManagedDnsDescriptor.java:29: error: package sun.net.spi.nameservice does not exist
        private static final sun.net.spi.nameservice.NameService nameService = new LocalManagedDnsProxy();
                                                    ^
/home/ec2-user/ngrinder/ngrinder-runtime/src/main/java/org/ngrinder/dns/LocalManagedDnsDescriptor.java:53: error: package sun.net.spi.nameservice does not exist
        public sun.net.spi.nameservice.NameService createNameService() {
                                      ^
/home/ec2-user/ngrinder/ngrinder-runtime/src/main/java/org/ngrinder/dns/LocalManagedDnsImpl.java:17: error: package sun.net.spi.nameservice does not exist
import sun.net.spi.nameservice.NameService;
                              ^
/home/ec2-user/ngrinder/ngrinder-runtime/src/main/java/org/ngrinder/dns/LocalManagedDnsImpl.java:29: error: cannot find symbol
public class LocalManagedDnsImpl implements NameService {
                                            ^
  symbol: class NameService
/home/ec2-user/ngrinder/ngrinder-runtime/src/main/java/org/ngrinder/dns/LocalManagedDnsProxy.java:16: error: package sun.net.spi.nameservice does not exist
import sun.net.spi.nameservice.NameService;
                              ^
/home/ec2-user/ngrinder/ngrinder-runtime/src/main/java/org/ngrinder/dns/LocalManagedDnsProxy.java:29: error: cannot find symbol
public class LocalManagedDnsProxy implements NameService {
                                             ^
  symbol: class NameService
/home/ec2-user/ngrinder/ngrinder-runtime/src/main/java/org/ngrinder/dns/LocalManagedDnsProxy.java:30: error: cannot find symbol
        private final NameService defaultDnsImpl = new LocalManagedDnsImpl();
                      ^
  symbol:   class NameService
  location: class LocalManagedDnsProxy
8 errors

**Comment by donggyu04** [comment]
@jinnyum what is your jdk version?

**Comment by jinnyum** [comment]
> @jinnyum what is your jdk version?

my java version : 

Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

**Comment by donggyu04** [comment]
Please use `1.8.x`

We'll support the higher version later.

**Comment by donggyu04** [comment]
#327 close with duplication.
