### ISSUE TITLE
Release new docker images for 3.4.2 to docker hub

### ISSUE THREAD

**Issue by JoelDamata-pcc** [naver/ngrinder#396]
The last release for the controller and agent docker hub images are 3.4 which was 3 years ago.

**Comment by donggyu04** [comment]
@JoelDamata-pcc 

Sorry, I missed docker image update. 
I will update that after finish current work.

**Comment by donggyu04** [comment]
@JoelDamata-pcc 

We uploaded the latest version `3.4.2` docker image.

![image](https://user-images.githubusercontent.com/14273601/59913904-1d39c600-9454-11e9-9231-15416a7f522d.png)
