### ISSUE TITLE
There are some errors reported when compiling locally.

### ISSUE THREAD

**Issue by chkch** [naver/ngrinder#400]
When compiling locally, I reported some errors. I guess it is because the jdk version is too high and incompatible. What is the version of jdk that developers use when developing locally?

**Comment by donggyu04** [comment]
@chkch 

Could you use JDK 1.8?

**Comment by chkch** [comment]
@donggyu04 
Yes, I can compile the master and develop branches using jdk1.8, but I can't compile and run the feature/convert-to-vuejs-script branch locally. I want to try this new version locally in advance, I can tell My way?

**Comment by donggyu04** [comment]
@chkch 
New version is only converting frontend framework, there is no function change.
nevertheless, if you want to run it locally.

you can run `NGrinderControllerStarter` with IDE and `npm run build` in `ngrinder-frontent` module
or
create executable jar(war) to contain files bundled with webpack under the static folder in main.

**Comment by chkch** [comment]
I found that some of the syntax in the file that created the mysql table structure seems to be a problem, please confirm

![Snipaste_2019-06-05_16-24-05](https://user-images.githubusercontent.com/31233516/58941465-6d572e00-87ae-11e9-801b-0c0bc21ccec7.png)

**Comment by chkch** [comment]
thx
