### ISSUE TITLE
I have a good idea on functionality and ease of use.

### ISSUE THREAD

**Issue by chkch** [naver/ngrinder#419]
I have a good idea on functionality and ease of use:
1, whether to consider adding a loop execution function (similar to crontab function)
2. The function of RPS is very practical during use. If it can be considered, refer to the constant passput Timer plugin of jmeter: https://jmeter.apache.org/usermanual/component_reference.html?spm=a2c4g.11186623.2 .13.2b802631ApLTWn#Constant_Throughput_Timer

@donggyu04

**Comment by donggyu04** [comment]
@chkch 

1. We don't have plan to include scheduling feature such as crontap.
you can use your server(such as jenkins) and ngrinder [REST API](https://github.com/naver/ngrinder/wiki/REST-API-PerfTest) for time scheduled test.

2. have no plan too, adjust throughput by adding appropriate sleep statement in your test function.
