### ISSUE TITLE
How to excute stress test with FIXED RPS for a period of time?

### ISSUE THREAD

**Issue by fengnex** [naver/ngrinder#423]
I have a question:
As mentioned in the topic, we want to do stress test in FIXED RPS for some time, which means that the RPS will be kept as certain value and will not change within the time range.

I wanna how to implement it with nGrinder?
thx

**Comment by songeunwoo** [comment]
hi
nGrindr is a target server's Maximum performance is a measurement tool, and Only random stress tests are possible.
So a fixed rps test is not possible.

**Comment by donggyu04** [comment]
@fengnex 

If you want to test at a specific TPS, adjust vuser.

**Comment by donggyu04** [comment]
@fengnex 

nGrinder isn't support this feature.
you can put appropriate sleep in your test script for make specific TPS.
