### ISSUE TITLE
Bad Set-Cookie header when fetching X-CSRF-Token in response headers 

### ISSUE THREAD

**Issue by shital1223** [naver/ngrinder#436]
Hi,
We have a get request which fetches xcsrf token in response header .But when i run this request in nGrinder with groovy script, it fails with the below error.

java.net.ProtocolException: Bad Set-Cookie header: JSESSIONID=E692A85CC1D0BCA66FE783850B571984; Path=/; Secure;, __VCAP_ID__=3a7aed88-309e-4850-5810-2df2; Path=/;, Secure
No '=' found for token starting at position 113

But the same request works perfectly fine when I fetch the csrf token using Postman client. Also works from Java program. So it can not be a server issue working differently for different clients.

Can anyone please help?

Regards!
Shital

**Comment by donggyu04** [comment]
@shital1223 

Could you add `https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient` lib and 
use them instead of `net.grinder.plugin.http.*` in your test function?

**Comment by donggyu04** [comment]
@shital1223 

It seems to the grinder http client bug.
refer to this link.  https://github.com/cossme/grinder/issues/28
you can use another http client as mentioned above.

**Comment by shital1223** [comment]
Thank you @donggyu04 
 I replaced the library suggested by you and it's working now. :)
