### ISSUE TITLE
Are you considering adding LDAP functionality to the new version?

### ISSUE THREAD

**Issue by chkch** [naver/ngrinder#437]
Hi, @donggyu04 , are you considering adding LDAP functionality to the new version?

**Comment by donggyu04** [comment]
@chkch 

Do you want to get login data from another resource (not use ngrinder DB)?

**Comment by chkch** [comment]
Yes, my team uses ldap or sso for unified authentication, which makes me a headache.
As far as I know, most teams are now using the unified authentication mode for team account management.

**Comment by junoyoon** [comment]
ngrinder supports plugin extension point which you can integrate your own sso.
We also are using our own plugin.

**Comment by donggyu04** [comment]
@chkch 

Check this guide https://github.com/naver/ngrinder/wiki/How-to-develop-plugin

**Comment by chkch** [comment]
thx

**Comment by junoyoon** [comment]
The plugin development guide will be updated within 1 weeks by our developers. please be patient.
