### ISSUE TITLE
Test is not terminating

### ISSUE THREAD

**Issue by shital1223** [naver/ngrinder#438]
Hi,

I have started a test with configuration:
1 agent, 1 process and 10 threads with,ramp-up(incremental step: 1 and interval: 1000ms)

that test is not terminating, even if i manually tried to stop test.

Does anybody have an idea how can i stop it?

Thanks,
Shital

**Comment by donggyu04** [comment]
@shital1223 

Is any logs in controller?

**Comment by shital1223** [comment]
@donggyu04 

below is the error logs (when i click on status):

Console is being prepared.
Console is started on port 12001
1 agents are starting.
1 agents are ready.
All necessary files are being distributed.
The total size of distributed files is over 976.6KBB.
- Safe file distribution mode is enabled by force.
- TestRunner.groovy
- resource1.txt
- lib/httpclient-4.5.8.jar
- lib/commons-logging-1.2.jar
- lib/httpcore-4.4.11.jar
- lib/commons-codec-1.11.jar
All necessary files are distributed.
The test is ready to start.
The test is started.

Script error
2019-07-16 04:38:46


Thanks,
Shital

**Comment by shital1223** [comment]
@donggyu04 

Detailed log:

[
  {
    "testName": "communicationLibwith10Threads",
    "tagString": "",
    "description": "",
    "status": "ABNORMAL_TESTING",
    "ignoreSampleCount": 0,
    "startTime": "Jul 16, 2019 4:39:18 AM",
    "targetHosts": "",
    "useRampUp": true,
    "rampUpType": "THREAD",
    "threshold": "R",
    "scriptName": "commWithContext/src/main/java/TestRunner.groovy",
    "duration": 60000,
    "runCount": 1,
    "agentCount": 1,
    "vuserPerAgent": 10,
    "processes": 1,
    "rampUpInitCount": 0,
    "rampUpInitSleepTime": 0,
    "rampUpStep": 1,
    "rampUpIncrementInterval": 1000,
    "threads": 10,
    "testErrorCause": "TESTING",
    "progressMessage": "\nConsole is being prepared.\nConsole is started on port 12001\n1 agents are starting.\n1 agents are ready.\nAll necessary files are being distributed.\nThe total size of distributed files is over 976.6KBB.\n- Safe file distribution mode is enabled by force.\n - TestRunner.groovy\n - resource1.txt\n - lib/httpclient-4.5.8.jar\n - lib/commons-logging-1.2.jar\n - lib/httpcore-4.4.11.jar\n - lib/commons-codec-1.11.jar\nAll necessary files are distributed.\nThe test is ready to start.\nThe test is started.\n",
    "testComment": "",
    "scriptRevision": 329,
    "stopRequest": true,
    "region": "NONE",
    "samplingInterval": 2,
    "param": "",
    "createdDate": "Jul 16, 2019 4:38:46 AM",
    "lastModifiedDate": "Jul 16, 2019 4:38:46 AM",
    "id": 1775
  }
]



Thanks,
Shital

**Comment by donggyu04** [comment]
@shital1223 

Is this still happened?

and then, `Safe file distribution mode is enabled by force.`
file distribution to the agent is slow when enable safe file distribution mode. 
this means that the test start time is delayed a lot.
you can modify ngrinder system configuration `controller.safe_dist_threshold` value big enough.

could you run using duration threshold? (not use runCount)

**Comment by shital1223** [comment]
Hi @donggyu04 

The issue is resolved now. our central team who has provisioned Ngrinder instance deleted that test.

Though when that test was running(infinitely) I was not able to start any test.
so how can I run new test for duration threshold ?

Also i want to run script which i created with groovy-maven  structure project, and it has other libraries like apache http client etc.  so i guess in order to process it by ngrinder i need to configure :

controller.safe_dist_threshold as suggested by you.

please correct me if have have assumed something wrong. and how can i configure this variable?



Thanks,
Shital

**Comment by donggyu04** [comment]
@shital1223 

If you access admin account you can modify ngrinder `System Configuration` at this menu.

![image](https://user-images.githubusercontent.com/14273601/61277411-17ce6200-a7ed-11e9-9051-ac36c8113e89.png)

duration threshold means that this.

![image](https://user-images.githubusercontent.com/14273601/61277317-ea81b400-a7ec-11e9-9a53-b773d6c5d3d1.png)
