### ISSUE TITLE
When modify maven.compiler.source to 1.8 we got issue in PerfTestServiceConfig.class

### ISSUE THREAD

**Issue by molihan** [naver/ngrinder#441]
when you modify your pom of below part.
`	<properties>
		<webappdir>${basedir}/src/main/webapp</webappdir>
		<deploy.dir>${basedir}/../../deploy</deploy.dir>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
`
Then you will got error in org.ngrinder.perftest.service.PerfTestServiceConfig and it says:
"ClusteredPerfTestService.class and PerfTestService.class are not imcompitable".
mainly it caused by the compiler language "level 7" doesn't check inheritation properly.

**Comment by molihan** [comment]
oh .~~ it seems you had already changed code. sorry for this ticket. let's close it.

**Comment by donggyu04** [comment]
@molihan 

Maven will be not used in the next version.
