### ISSUE TITLE
How do you dynamically start and stop the pressure

### ISSUE THREAD

**Issue by WANGJIANGA** [naver/ngrinder#494]
How do you dynamically start and stop the pressure

**Comment by donggyu04** [comment]
@WANGJIANGA 

Do you want adjust load(vuser) without stopping test?

**Comment by WANGJIANGA** [comment]
> @WANGJIANGA
> 
> 您想在不停止测试的情况下调整负载(Vuser)吗？

对的，是这个意思

**Comment by WANGJIANGA** [comment]
> @WANGJIANGA
> 
> Do you want adjust load(vuser) without stopping test?

yes

**Comment by donggyu04** [comment]
@WANGJIANGA 

You can use `ramp up` option to gradually increase the load, and control load in script using some function like `sleep`.
but adjust `vuser` count dynamically isn't possible.

**Comment by WANGJIANGA** [comment]
> @WANGJIANGA
> 
> 你可以用`ramp up`逐步增加的选项`vuser`或者使用如下函数在脚本中控制加载`sleep`.
> 但调整`vuser`动态计数是不可能的。

Want to add a dynamic stop start thread function to achieve this effect

> @WANGJIANGA
> 
> You can use `ramp up` option to gradually increase `vuser` or control load in script using some function like `sleep`.
> but adjust `vuser` count dynamically isn't possible.

Want to add a dynamic stop  start thread function to achieve this effect

**Comment by donggyu04** [comment]
@WANGJIANGA 

Unfortunately, functionality you want seems impossible.

**Comment by WANGJIANGA** [comment]
> @WANGJIANGA
> 
> Unfortunately, functionality you want seems impossible.

why...?

**Comment by donggyu04** [comment]
@WANGJIANGA 


When the performance test is run,  nGrinder make process and thread(vuser) from your test configuration.
and just run your script code until the end of the test.

While the test is running, nGrinder doesn't support  reduce already running threads.

> As mentioned above, if you increment thread gradually using ramp up

**Comment by songeunwoo** [comment]
nGrinder is there to test the maximum performance of the target server.
If you want to change the test setup, separate each test.

**Comment by WANGJIANGA** [comment]
> @WANGJIANGA
> 
> When the performance test is run, nGrinder make process and thread(vuser) from your test configuration.
> and just run your script code until the end of the test.
> 
> While the test is running, nGrinder doesn't support reduce already running threads.
> 
> > As mentioned above, if you increment threads gradually using ramp up

Instead of decreasing, stop dynamically during the pressurization process, start threads increase.

**Comment by WANGJIANGA** [comment]
> nGrinder is there to test the maximum performance of the target server.
> If you want to change the test setup, separate each test.

Instead of decreasing, stop dynamically during the pressurization process, start threads increase.

**Comment by donggyu04** [comment]
@WANGJIANGA 

As @songeunwoo already said,  you can't be run again after stop and changing the setting.
you must create another test.
