### ISSUE TITLE
Index-Developer Resources-More... Open link error

### ISSUE THREAD

**Issue by lingsoul** [naver/ngrinder#508]
@donggyu04 
Hi~I found a mistake on ngrinder3.5.0
branch : remotes/origin/feature/support-git
filePath:  ngrinder/ngrinder-frontend/src/js/components/Home.vue
at line 20
"seeMoreQuestionUrl" Should be replaced with "seeMoreResourcesUrl".

**Comment by donggyu04** [comment]
@lingsoul 
You can create PR for this.
I will fix it if you don't.

Thanks.

**Comment by donggyu04** [comment]
#518
