### ISSUE TITLE
can not start ngrinder-monitor   [ 3.3 ]

### ISSUE THREAD

**Issue by koy1123** [naver/ngrinder#51]
first of all,  this tool is awesome !   thanks for your great job,  really enjoy using it
the controller and agent works very well on my machine   
just got below error when I try to start a monitor agent with default agent.conf.  can any one help on this?

![image](https://cloud.githubusercontent.com/assets/1849184/3268318/4867b0d2-f2db-11e3-9062-57e5e555d384.png)

**Comment by junoyoon** [comment]
Dup with #43
Fixed by 822aa96b
