### ISSUE TITLE
test Basic Configuration，Scroll bar slide error

### ISSUE THREAD

**Issue by lingsoul** [naver/ngrinder#525]
Hi~ @donggyu04 ，Sorry to disturb you.
Performance Test--test Configuration--Basic Configuration--Duration，Click on the 'duration' scroll bar to slide slowly to the right，shows error message:  Please enter a value greater than or equal to 1.

my system.conf
controller.max_run_hour=72

**Comment by donggyu04** [comment]
@lingsoul 

Fixed at https://github.com/naver/ngrinder/pull/524/commits/0a6c8bb5724577834fc40269c8dbab41be31c879
