### ISSUE TITLE
ngrinder-core repo should be included in pom.xml

### ISSUE THREAD

**Issue by jasonyeong790** [naver/ngrinder#533]
pom.xml in ngrinder-3.4.4 (root folder)

Without repo below, it cannot be packaged properly

```
<repository>
    <id>ngrinder-core</id>          
    <url>https://github.com/nhnopensource/nhnopensource.maven.repo/raw/master/releases/</url>
</repository>
```

Best Regard

**Comment by donggyu04** [comment]
@jasonyeong790 


Hi, thanks for using nGrinder.
Can you answer some questions?

1. Which version are you using?
2. Does package mean Maven Goal?

> https://github.com/nhnopensource/nhnopensource.maven.repo/raw/master/releases/ is old repository. from version 3.4 of nGrinder, please use https://github.com/naver/ngrinder/raw/ngrinder.maven.repo/releases

**Comment by jasonyeong790** [comment]
Hey

1. Sorry, I forgot. 3.4.4 the newest one 

2. Exactly 

Sincerely

**Comment by donggyu04** [comment]
@jasonyeong790 

Run `install-maven-lib.sh` first before package.

**Comment by jasonyeong790** [comment]
Thanks ! 

But unfortunately, It gives same the result after I run it.

I think the mvn cannot find the exact same repo which the ngrinder-patch comes from. 

It only works when I add the specific repo in pom.xml like above

**Comment by jasonyeong790** [comment]
If I omit the repo info, it will give the error like below. 

[ERROR] Failed to execute goal on project ngrinder-starter: Could not resolve dependencies for project org.ngrinder:ngrinder-starter:jar:3.4.4: Failure to find grinder:grinder-patch:jar:3.9.1-patch in https://repo.springsource.org/release was cached in the local repository, resolution will not be reattempted until the update interval of springsource-repo has elapsed or updates are forced ->

**Comment by donggyu04** [comment]
@jasonyeong790 

If you run `install-maven-lib.sh` correctly `grinder:grinder-patch:jar:3.9.1-patch` is installed your local repository like below, could you check this?

![image](https://user-images.githubusercontent.com/14273601/78115833-591ba600-743e-11ea-8d7c-695c0d31508c.png)

I run `./mvnw clean package -DskipTests` everything is fine.

> I recommend using `mvnw` to resolve maven version problem you may have.

**Comment by jasonyeong790** [comment]
Dear @donggyu04 

Thank you so much. It works for me. 

I wish you all the best :)

Best Regard
