### ISSUE TITLE
Dependencies copy in pom.xml is failed.

### ISSUE THREAD

**Issue by Kim-LL** [naver/ngrinder#541]
groovy-maven-parent/pom.xml is being written in *** for test 0
Dependencies copy in groovy-maven-parent/pom.xml is failed.
最简单原因，我编译测试的时候 pom.xml 没有复制过去，这个问题 我发现从3.4.0 到最新版本都有这个问题，我试了好多机器也都是有这个问题，你们都是怎么解决的，也就是 groovy maven 项目没办法使用

**Comment by donggyu04** [comment]
@Kim-LL 

Could you response some question?

1. Are you saying that groovy maven script doesn't work?
2. What ngrinder version are you using?

**Comment by imbyungjun** [comment]
Could you let us know your pom.xml?

I think that the problem could be caused by HTTP EOL of maven central repository.

**Comment by Kim-LL** [comment]
Yes!

When I'm done creating the project, I'm done writing the script, tab validate script.

Console display
”“”
Copy dependencies by running 'mvn dependency:copy-dependencies -DoutputDirectory=./lib -DexcludeScope=provided'


Dependencies copy in groovy-maven-parent/pom.xml is failed.
“”“
The ngrinder version I used: 3.4.4  and tomcat version 8.5.40. java version 1.8.0_211 
I guess this is because there is a problem copying the pom.xml file.
I'm going into the server background and Into the ~ /. Ngrinder/script / {user}/ path.
I found that everything exists except the pom file

At 2020-04-22 09:52:37, "leedonggyu" <notifications@github.com> wrote:

@Kim-LL

Could you response some question?

Are you saying that groovy maven script doesn't work?
What ngrinder version are you using?

**Comment by Kim-LL** [comment]
sure
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">


    <modelVersion>4.0.0</modelVersion>
    <groupId>com.test</groupId>
    <artifactId>performance</artifactId>
    <version>0.0.1</version>


    <properties>
        <ngrinder.version>3.4.4</ngrinder.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring.framework.version>5.2.2.RELEASE</spring.framework.version>
        <fastjson.version>1.2.59</fastjson.version>
    </properties>




    <repositories>
        <repository>
            <id>ngrinder.maven.repo</id>
            <url>https://github.com/naver/ngrinder/raw/ngrinder.maven.repo/releases</url>
        </repository>
    </repositories>


    <dependencies>


        <dependency>
            <groupId>org.ngrinder</groupId>
            <artifactId>ngrinder-groovy</artifactId>
            <version>${ngrinder.version}</version>
            <scope>provided</scope>
        </dependency>


        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>${spring.framework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>${spring.framework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.framework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>${spring.framework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <version>${spring.framework.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>${fastjson.version}</version>
        </dependency>




    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-eclipse-plugin</artifactId>
                <version>2.9</version>
                <configuration>
                    <additionalProjectnatures>
                        <projectnature>
                            org.eclipse.jdt.groovy.core.groovyNature
                        </projectnature>
                        <projectnature>
                            org.eclipse.m2e.core.maven2Nature
                        </projectnature>
                    </additionalProjectnatures>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
















At 2020-04-22 10:15:44, "Imbyungjun" <notifications@github.com> wrote:

Could you let us know your pom.xml?

I think that the problem could be caused by HTTP EOL of maven central repository.

**Comment by Kim-LL** [comment]
I got the root cause
I added a private dependency
<dependency>
    <groupId>com.moji</groupId>
    <artifactId>moji-location-api</artifactId>
    <version>1.0.1</version>
    <type>jar</type>
</dependency>
It works fine when I remove this dependency
This is the company's private repository. 
I tried to specify my maven settings.xml file.  added JAVA_OPTS="-Dmaven. Home =/root/apache-maven-apache-maven-3.6.0" to the catalina.sh file. 
But ngrinder did not seem to know it.
My current environment
java version: 1.8.0_242
tomcat version: 8.5.40
ngrinder version: 3.4.4
How can I edit the settings.xml for maven that comes with the ngrinder?

At 2020-04-22 10:15:44, "Imbyungjun" <notifications@github.com> wrote:

Could you let us know your pom.xml?

I think that the problem could be caused by HTTP EOL of maven central repository.

**Comment by donggyu04** [comment]
@Kim-LL 

You can make `lib` directory on same depth to your test scripts.
and upload jar you want.

`lib` will be add in classpath to your worker process

**Comment by Kim-LL** [comment]
Thanks your answer。
That really solved my problem。
Excuse me,

The ngrinder version: 3.4.4 can read the local maven settings.xml  file?







At 2020-04-23 10:50:03, "leedonggyu" <notifications@github.com> wrote:

@Kim-LL

You can make lib directory on same depth to your test scripts.
and upload jar you want.

lib will be add in classpath to your worker process

**Comment by donggyu04** [comment]
@Kim-LL 

nGrinder using `maven-embedder(3.6.3)` for `maven groovy scripts`.
I guess you should modify `setting.xml` in below path
`{home}/.m2/wrapper/dists/apache-maven-3.6.3-bin/.../apache-maven-3.6.3/conf/setting.xml`

**Comment by donggyu04** [comment]
@Kim-LL 

Put `settings.xml` in `.m2`. 
I work fine.

**Comment by Kim-LL** [comment]
Thanks!













At 2020-04-24 10:08:16, "leedonggyu" <notifications@github.com> wrote:

@Kim-LL

Put settings.xml in .m2.
I work fine.
