### ISSUE TITLE
Running n-grinder tests via cmd prompt or integrating in jenkins build pipeline

### ISSUE THREAD

**Issue by Prashantha1** [naver/ngrinder#546]
Dear Colleagues,
I have the requirement where I have to integrate n-grinder in my Jenkins build pipeline. Is this possible? If yes, please could you provide example script or some code which you have used earlier.

So that I can refer the same and modify accordingly to launch n-grinder via command promt/jenkin job and execute scripts and capture the results.

Please provide your help.

Thanks
Prashantha

**Comment by donggyu04** [comment]
@Prashantha1 

We support some [rest APIs.](https://github.com/naver/ngrinder/wiki/REST-API)
you can trigger nGrinder test in Jenkins using http plugin, or in cmd using curl.
