### ISSUE TITLE
How to cache test files for Agent

### ISSUE THREAD

**Issue by casyFire** [naver/ngrinder#547]
Hi:
    When i start a test, the test files will transport from controller to agent，but i hope agent can cache the files when files is same. Can you give me some advice？

**Comment by donggyu04** [comment]
@casyFire 

Agent file cache will be support next release.
https://github.com/naver/ngrinder/pull/519 : relevant PR

You can distribute your resource to agent machine and access that in scripts

**Comment by casyFire** [comment]
Ok, thanks for your advice

**Comment by casyFire** [comment]
When will the new version be released?
