### ISSUE TITLE
What is the max file size for a perttest?

### ISSUE THREAD

**Issue by casyFire** [naver/ngrinder#548]
Hi:
    In some cases, i need to use very large file to start a perftest, for example: 1G, but it throw oom exception, i want to know the max file size ngrinder support? And can you give me some advise for those cases?

**Comment by donggyu04** [comment]
@casyFire 

Could you modify agent option?
it's in {agent_home}/__agent.conf file.

![image](https://user-images.githubusercontent.com/14273601/81538098-35d30780-93a9-11ea-8967-ba40dd6d70e3.png)

**Comment by casyFire** [comment]
ok. i will try it, thank you
