### ISSUE TITLE
static properties defined cannot be reused

### ISSUE THREAD

**Issue by Kim-LL** [naver/ngrinder#552]
private static ApplicationContext context
    private static TacticsService tacticsService
    private static GTest test

    @BeforeProcess
    static void beforeProcess() {
        test = new GTest(1, "RPC-TacticsService-Test")
        context = new ClassPathXmlApplicationContext("classpath:app-context.xml")
        tacticsService = context.getBean(TacticsService.class)
     }
    @Test
    void testGetTacticsInfo(){
            grinder.logger.info("tacticsService: " + tacticsService)
    }

进行压测的时候，这个 tacticsService 都会被重新初始化，不能复用，如何解决？
During the pressure test，I although initialized TacticsService in beforeProcess, But it is still being reinitialized
tacticsService: com.test.performance.service.TacticsService$Client@1cd09ec9
tacticsService: com.test.performance.service.TacticsService$Client@28bf783b
tacticsService: com.test.performance.service.TacticsService$Client@41899724
How can I initialize only once？Make it reusable and improve the pressure measurement performance！！

**Comment by donggyu04** [comment]
@Kim-LL 

`@BeforeProcess` is called just one time when before the process is invoked.
so `tacticsService = context.getBean(TacticsService.class)` this code run just one time each process.

base on below logs, could you check inner class `Client` is re-initialize in  `TacticsService` of some reason?

````
tacticsService: com.test.performance.service.TacticsService$Client@1cd09ec9
tacticsService: com.test.performance.service.TacticsService$Client@28bf783b
tacticsService: com.test.performance.service.TacticsService$Client@41899724
````

**Comment by Kim-LL** [comment]
It's the service factor on our side




Thank you for your reply







At 2020-05-13 14:24:14, "leedonggyu" <notifications@github.com> wrote:

@Kim-LL

@BeforeProcess is called just one time when before the process is invoked.
so tacticsService = context.getBean(TacticsService.class) this code run just one time each process.

base on below logs, could you check inner class Client is re-initialize in TacticsService of some reason?

tacticsService: com.test.performance.service.TacticsService$Client@1cd09ec9
tacticsService: com.test.performance.service.TacticsService$Client@28bf783b
tacticsService: com.test.performance.service.TacticsService$Client@41899724
