### ISSUE TITLE
Run version 3.5.0, liquibase.exception.ValidationFailedException: Validation Failed

### ISSUE THREAD

**Issue by lingsoul** [naver/ngrinder#596]
Run version 3.5.0, liquibase.exception.ValidationFailedException: Validation Failed
I want to save the old data. How can I operate it

**Comment by lingsoul** [comment]
![image](https://user-images.githubusercontent.com/22099083/86592841-c18e9c00-bfc6-11ea-92a1-d6ba6b3b51bf.png)

**Comment by donggyu04** [comment]
@lingsoul 

It seems to happen because `db.changelog_schema_MYSQL.xml` file is changed from new commit.

1. Update changed database schema manually(not using liquibase auto update).
2. Update `MD5SUM` column to `7:83ff87b1dcdf36c47bcf5e514a84e30d'` in `DATABASECHANGELOG` table.
