### ISSUE TITLE
Need a way to compare test runs

### ISSUE THREAD

**Issue by bbbco** [naver/ngrinder#60]
It would be nice to have some way to compare two or more test runs. 

 - The comparison should show relevant data compared across test runs
 - The comparison should show a single chart with data acrued across test runs

**Comment by junoyoon** [comment]
It's already supported. If you provide a tag to two test and search the perftest with the given tag. It will show two test in the perf test list page. Then if u can click "show chart" button on the right side, you can see the brief charts on the test. It can show the multiple test in a single page.
 
<img width="946" alt="20160419154146" src="https://cloud.githubusercontent.com/assets/1000705/14629970/4da3546e-0645-11e6-895e-0d934f6504fc.png">
