### ISSUE TITLE
Make UI consistent

### ISSUE THREAD

**Issue by junoyoon** [naver/ngrinder#615]
![image](https://user-images.githubusercontent.com/1000705/88883570-a7677700-d26f-11ea-9698-74b14369522a.png)
![image](https://user-images.githubusercontent.com/1000705/88883579-ad5d5800-d26f-11ea-8721-c15f85816b8a.png)
![image](https://user-images.githubusercontent.com/1000705/88883591-b3ebcf80-d26f-11ea-9f67-9fa1d5f9e5b8.png)
![image](https://user-images.githubusercontent.com/1000705/88883600-ba7a4700-d26f-11ea-92fd-cb2cc3a77af9.png)

currently, each page's table bar contains little different ui element and order.

We should make them consistent like followings.
1. ui order
    * search input box >  additional info > action buttons
2. use same ui style
    * please add search button just next to input box (do not put space b/w them)

**Comment by donggyu04** [comment]
@junoyoon 

`2. use same ui style` is already [changed](https://github.com/naver/ngrinder/pull/614#issue-458855258).

**Comment by junoyoon** [comment]
Okay.
