### ISSUE TITLE
Agent cant't connect to controller on port 12001

### ISSUE THREAD

**Issue by tianyj** [naver/ngrinder#62]
hi~
I use the ngrinder 3.3 on centos  7. I start the controller sucess. and It  can find agent(host is 192.168.2.110).
When I start a test.The agents logs that it can't connect to controller on port  /192.168.2.3:12001.
The fileware is open on 12000~12000+, I use 'telnet 192.168.2.3 12001' on the ngrinder controller server(host is 192.168.2.3), it is failed. use 'telnet 127.0.0.1 12001' ,it is ok!
I use 'netstat apn|grep 12001' I find 12001 is binded on 127.0.0.1, 'netstat apn|grep 16001' it is binded 192.168.2.3
so, I want to know how to bind port 12001 on host 192.168.2.3 like port 16001.
How to config the controller params?
Thanks~

**Comment by GwonGisoo** [comment]
config in system.conf

controller.console_port_base=12001
if you set 12001, console used 12001~12010
console count is default 10, you can config "controller.max_concurrent_test" param

**Comment by tianyj** [comment]
thanks!
I test controller.console_port_base=12001, it also bind on host 127.0.0.1.
And I run controller on windows, it works ok.

**Comment by GwonGisoo** [comment]
welcome! Thank you for using nGrinder.
