### ISSUE TITLE
Agent tries to connect to 127.0.0.1

### ISSUE THREAD

**Issue by nmodin** [naver/ngrinder#63]
Hi,

I just downloaded/installed nGrinder for evaluation. It seems the agent is trying to connect to a controller using 127.0.0.1.

    2015-04-13 01:33:32,732 INFO  starter: connecting to controller 127.0.0.1:16001
    2015-04-13 01:33:32,746 INFO  agent controller daemon: The agent controller daemon is started.
    2015-04-13 01:33:32,768 ERROR agent controller: Error while connecting to agent controller server at /127.0.0.1:16001

I assume this isn't the expected behaviour according to the docs:

*Not like previous nGrinder, nGrinder 3.3 agents is downloaded from the controller. The downloaded agent package already contains the default agent configuration connecting to the controller from which the agent is downloaded. 
So just unpacking the tar file and running “run_agent.sh” or “run_agent.bat” make the agent connect to the controller.*

Looking on the agent side I found this in agent.conf which I assumed was the culprit:
**agent.controller_host=localhost**

Now this is where it gets interesting ...

I changed this to point to my controller IP. This however is overwritten when I start the agent, and it reverts back to localhost.

I've attached files showing the before-and-after shots of the agent reverting my changes:
![screen shot 2015-04-13 at 10 53 31](https://cloud.githubusercontent.com/assets/1699834/7112604/8b646c42-e1cb-11e4-9d73-ca0db71897ca.png)

 
What am I missing here. Any pointers on how to get this show on the road ? :)

Cheers,
Niklas

**Comment by GwonGisoo** [comment]
Hi, nmodin.

I think this problem have been caused by overwriting "agent.conf"

### Try next step for resolve.

1. change file "~/ngrinder_agent/__agent.conf"
> agent.controllr_host=10.161.159.209
2. run with overwrite option
> ~/ngrdiner_agent/run_agent.sh -o
3. check console log and "~/.ngrinder_agent/agent.conf"

If you can't config... please reply

**Comment by nmodin** [comment]
Hi,

Yep that took care of the issue. :)

Just to clarify I must still configure this on all agents after unpacking the agent tar downloaded from the controller ?

Perhaps this should be updated in the documentation, as right now this is explicitly stated as a feature (a very nice feature actually :) )

Cheers,
Niklas

**Comment by GwonGisoo** [comment]
Hi,

This issue occurs when you modify the "~/.ngrinder_agent/agent.conf".
(correctly, agent.conf last modified time greater than __agent.conf)
We will resolve this issue :)

Thanks Niklas!

**Comment by GwonGisoo** [comment]
Fixed @411f4c39
