### ISSUE TITLE
ngrinder3.5 version Web page jitters below resolution (1230-1243)*869

### ISSUE THREAD

**Issue by jeff526** [naver/ngrinder#631]
ngrinder3.5 version Web page jitters below resolution (1230-1243)*869
![ngrinder35](https://user-images.githubusercontent.com/7038589/89869746-606e6f80-dbe7-11ea-8d86-6b5ea57e8d57.png)

**Comment by donggyu04** [comment]
@jeff526 

Could you attach your capture?

**Comment by jeff526** [comment]
#

**Comment by jeff526** [comment]
#
![ngrinder35](https://user-images.githubusercontent.com/7038589/89870038-d96dc700-dbe7-11ea-9d0f-49e830670fe7.png)

**Comment by jeff526** [comment]
Steps to reproduce
1. Start chrom
  2. Open the ngrinder page
3. Press F12
4. Adjust the chrom page size length*width (1230-1243)*869
5. Browser page jitter
