### ISSUE TITLE
[Help]  请帮助纠正中文信息

### ISSUE THREAD

**Issue by donggyu04** [naver/ngrinder#634]
你好
想向 ngrinder 用户求助。

前不久推出的新版本中，中文信息没有写好。
如果您能帮助在中国用户中撰写信息，我们将不胜感激。

期待PR。:)
谢谢。

[messages_en.properties](https://github.com/naver/ngrinder/blob/develop/ngrinder-controller/src/main/resources/messages_en.properties)
[messages_cn.properties](https://github.com/naver/ngrinder/blob/develop/ngrinder-controller/src/main/resources/messages_cn.properties)

```
common.user=User
common.list=List
perfTest.message.save.error=Test save is failed.
perfTest.message.saveAndRun.error=Test save and run is failed.
perfTest.message.downloadCSV.error=Error while download CSV.
perfTest.message.scm=Scm is required.
perfTest.message.scheduled.success=Perftest has been scheduled successfully.
perfTest.config.ignoreTooManyError=Ignore Errors
perfTest.config.ignoreTooManyError.help=If you want to continue testing even if too many errors occur. Please check this.
perftest.status.checkout_script=Prepare script
script.message.empty.github.config=Please enter your github configuration.
script.github.add.config=Add github
user.message.delete.error=User(s) deletion is failed.
user.message.save.success=User save success.
user.message.save.error=User save is failed.
```

```
common.user=
common.list=
perfTest.message.save.error=
perfTest.message.saveAndRun.error=
perfTest.message.downloadCSV.error=
perfTest.message.scm=
perfTest.message.scheduled.success=
perfTest.config.ignoreTooManyError=
perfTest.config.ignoreTooManyError.help=
perftest.status.checkout_script=
script.message.empty.github.config=
script.github.add.config=
user.message.delete.error=
user.message.save.success=
user.message.save.error=
```

**Comment by lijie1010** [comment]
我先抢个沙发，抛转引入吧。哈哈


common.user=User
common.list=List
perfTest.message.save.error=保存失败。
perfTest.message.saveAndRun.error=保存并运行失败。
perfTest.message.downloadCSV.error=下载CSV文件时发生错误。
perfTest.message.scm=缺少Scm。
perfTest.message.scheduled.success=Perftest定时任务设置成功
perfTest.config.ignoreTooManyError=忽略错误
perfTest.config.ignoreTooManyError.help=错误发生时继续运行测试，请选择该选项。
perftest.status.checkout_script=准备脚本
script.message.empty.github.config=请您输入github配置信息。
script.github.add.config=添加github
user.message.delete.error=用户删除失败。
user.message.save.success=用户保存成功。
user.message.save.error=用户保存失败。

**Comment by donggyu04** [comment]
@lijie1010 

Thanks 👍

**Comment by junoyoon** [comment]
Thx
