### ISSUE TITLE
run run_ agent.sh,  '__agent.conf' be deleted

### ISSUE THREAD

**Issue by lingsoul** [naver/ngrinder#671]
Version 3.5.2, run run_ agent.sh or run_monitor.sh '__agent.conf' be deleted ,and  ' sh run_ agent.sh -o ' does not take effect

**Comment by donggyu04** [comment]
That feature is deleted because users are often confused about using the -o option.

please modify agent configuration at `{agent_home}/agent.conf` directly.

**Comment by lingsoul** [comment]
Hi~ @donggyu04 ,Thank you very much for your answer

After running agent.conf Will be covered. Here are my steps:

1. sh run_agent.sh  ngrinder-agent/__agent.conf --> {agent_home}/agent.conf  
2. sh run_monitor.sh  ngrinder-monitor/__agent.conf --> {agent_home}/agent.conf  

The last {agent_home}/agent.conf content:

common.start_mode=monitor
# If you want to monitor bind to the different local ip not automatically selected ip. Specify below field.
#monitor.binding_ip=hostname_or_ip
monitor.binding_port=13243
