### ISSUE TITLE
3.5.2 버전 기동시 오류..

### ISSUE THREAD

**Issue by ahnjunwoo** [naver/ngrinder#680]
여기다가 써도 될지 모르겟지만.. 
jdk 11버전으로 에이전트랑 컨트롤러를 기동까지는 정상적으로 되는데 요청시 아래와 같이 에러가 발생하는데 이유를 알수있을까요?
![스크린샷 2020-10-28 오후 2 07 35](https://user-images.githubusercontent.com/5328073/97395249-df8e5c80-1927-11eb-82cd-675a0b624f17.png)
<img width="1370" alt="스크린샷 2020-10-28 오후 2 12 11" src="https://user-images.githubusercontent.com/5328073/97395289-f339c300-1927-11eb-9bf2-1ebd052e8539.png">

mac os 로컬에서 다운받아 naver로 요청하는 테스트를 하는데(처음 테스트) 위 스샷처럼 에러가 발생하네요.

**Comment by donggyu04** [comment]
@ahnjunwoo 

안녕하세요. 
사용하시는 mac os 버전 & JDK 11 버전이 어떻게 되시나요?

로그상으론 테스트에 필요한 싱글 콘솔이 정상적으로 준비되지 못한 것 같은데요.
다음 순서로 한번 실행시켜 보시기 바랍니다.

1. `{USER_HOME}/.ngrinder/system.conf`  삭제
2. https://github.com/naver/ngrinder/releases/download/ngrinder-3.5.2-20200929/ngrinder-controller-3.5.2.war 다운로드
3. `java -jar ngrinder-controller-3.5.2.war`
4. admin/admin 접속 후 에이전트 다운로드 & 실행.
5. 테스트

> 스크립트 테스트 시 naver로 호출을 하지 마시고, 단순 sleep(1000); 구문을 넣어 테스트 하시거나 사용자 웹 서버로 호출 부탁드립니다.

**Comment by ahnjunwoo** [comment]
openjdk version "11.0.8"
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
입니다.

**Comment by ahnjunwoo** [comment]
네 감사힙니다.
