### ISSUE TITLE
위키에는 기여할 수 없나요?

### ISSUE THREAD

**Issue by kdw9502** [naver/ngrinder#696]
[커밋](https://github.com/kdw9502/ngrinderwiki/commit/c7a9cb7536d354f4df74bf3e5c220f4b878f6849)
위의 커밋과 같이 위키에 Jython 스크립트에서의 Native Library Binding 내용을 추가하고 싶습니다.

**Comment by junoyoon** [comment]
감사합니다. @donggyu04 님 반영 해주세요.

**Comment by donggyu04** [comment]
@kdw9502 

감사합니다. wiki는 별도 처리를 해주지 않으면 PR을 할 수 없는 구조라 제가 수정 후 author를 변경해 드렸습니다~

<img src="https://user-images.githubusercontent.com/14273601/101330336-d1801400-38b5-11eb-8c64-b2a885accc54.png" width="370" height="250" />
