### ISSUE TITLE
different numbers in detailed log

### ISSUE THREAD

**Issue by thinkong** [naver/ngrinder#70]
Hi

I am currently testing my server with ngrinder
Recently I ran ngrinder for 5 minutes and the following results showed up

name | number
------------|-------------------------
 Executed Tests | 109,666 
 Successful Tests | 109,666 

but then when i checked my DB it showed 110936 data being inserted... 

so i checked the log for this test and it showed..
`````
           Tests        Errors       Mean Test    Test Time    TPS          Mean         Response     Response     Mean time to Mean time to Mean time to 
                                       Time (ms)    Standard                  response     bytes per    errors       resolve host establish    first byte   
                                                    Deviation                 length       second                                 connection                
                                                    (ms)                                                                                                    

Test 1       110936       0            2.52         1.39         372.02       264.00       98213.29     0            0.02         0.18         2.47          "127.0.0.1"

Totals       110936       0            2.52         1.39         372.02       264.00       98213.29     0            0.02         0.18         2.47         
`````

I was wondering why the summary number is different then the log.. it this normal? am i doing something wrong?

any help would be great

**Comment by junoyoon** [comment]
The log includes only one process result. I made this limitation due to the size of logs

**Comment by thinkong** [comment]
@junoyoon
log results have  a bigger number then detailed results... if the log only showed one process shouldnt the numbers in the log be smaller then the detailed numbers?

로그에 있는 숫자가 테스트 상세 정보에 나오는 숫자보다 큰게 정상인건가요?

**Comment by grubbyhou** [comment]
@thinkong @junoyoon 
I have met the same problem with you. Have you find a way to figure it out? 
I doubt that the console port closed too early and some message from agent have not recevied?

**Comment by junoyoon** [comment]
Yes... it's little bit different.. because ngrinder controller metric collection is stopped little before actual run is stopped. If u want to run exact number of tests, please use run count based test running.

**Comment by junoyoon** [comment]
Anyway.. we will fix this next version..

**Comment by grubbyhou** [comment]
thank u for ur answer!  
Have you got a plan to fix that? I wanto use that in my project.

**Comment by InH4te** [comment]
Anyupdate on this?
Because we are running the tests by the run count. But still the number of Executed tests from the summary in the UI is different from the logs.
Any idea when this will be fixed?

**Comment by renhongchao** [comment]
Anyupdate?

**Comment by junoyoon** [comment]
No update yet. We're currently rewriting UI layer first. 
Then we will fix this issue.

**Comment by renhongchao** [comment]
first , thank u for your answer!
Just like you say,  ngrinder controller metric collection is stopped little before actual run is stopped.
May i change the metric collection stop time  and  let it collect all data ?  Any suggestion?

**Comment by junoyoon** [comment]
U can send PR for it.

**Comment by renhongchao** [comment]
i will try .
