### ISSUE TITLE
Use discussion instead of nabble

### ISSUE THREAD

**Issue by junoyoon** [naver/ngrinder#700]
Gitub opened the discussion feature. see https://github.com/naver/ngrinder/discussions
I think it's better to move our previous nabble forum to there.

Check the api which we can get the discussion topics from github to show them in ngrinder front page

**Comment by donggyu04** [comment]
@junoyoon 

I try to find discussion API but, It seems not exist. (only [team discussion API](https://docs.github.com/en/free-pro-team@latest/rest/reference/teams#list-discussions) is available)
Maybe, this feature is beta version now. so It seems not supported yet.

<img src="https://user-images.githubusercontent.com/14273601/102206939-ada17b80-3f10-11eb-8c57-7110584a2bf5.png" width="400" height="95" />

**Comment by donggyu04** [comment]
Due to the API requires authentication, It was decided to drop.
