### ISSUE TITLE
ERROR in ./src/js/entries/app.js Module build failed (from ./node_modules/babel-loader/lib/index.js): Error: Cannot find module '@babel/plugin-transform-arrow-functions' from 'D:\ngrinder\ngrinder-ngrinder-3.5.3-20201127\ngrinder-frontend'

### ISSUE THREAD

**Issue by demonchm** [naver/ngrinder#704]
ERROR in ./src/js/entries/app.js Module build failed (from ./node_modules/babel-loader/lib/index.js): Error: Cannot find module '@babel/plugin-transform-arrow-functions' from 'D:\ngrinder\ngrinder-ngrinder-3.5.3-20201127\ngrinder-frontend'

**Comment by imbyungjun** [comment]
Which command did you run when you getting that error?
You need to explain more about the error environment.

**Comment by demonchm** [comment]
> Which command did you run when you getting that error?
> You need to explain more about the error environment.

build bootWar

**Comment by donggyu04** [comment]
@demonchm 

Try `npm install` first before gradle build.(`gradlew clean build -x test`)

**Comment by imbyungjun** [comment]
It's better to use `gradlew`.
The build result will be placed on `${NGRINDER_SOURCE_HOME}/ngrinder-controller/build/libs/`.
