### ISSUE TITLE
groovy 2 depth 자료는 어떻게 POST 날려야하나요 ?

### ISSUE THREAD

**Issue by yousung-ahn** [naver/ngrinder#708]
안녕하세요 ~

일반적인 방법으로는 POST를 잘 보내겠는데요.
`new NVpair("key", "value");`

뎁스가 있는 경우에는 어떻게 해야하는지 잘모르겠습니다. groovy  입니다.

`
{
    "data" : {
          "key1: "value",
          "key2": "value"
     }
}
`

현재 저의코드는 

`
ObjectMapper mapper = new ObjectMapper();
String jsonMapper = mapper.writeValueAsString([
		"content_product_no" : product.getContentNo(),
		"product_no" : product.getNo(),
]);

params = [
		      new NVPair("cart_items", jsonMapper)
]
`

이렇습니다.

**Comment by donggyu04** [comment]
@yousung-ahn 

안녕하세요.
아래와 같이 호출해주시면 됩니다.

```
headers = [new NVPair("Content-Type", "application/json")] as NVPair[]
...
def param = "{\"name\": \"hello\",\"age\": 100}"
request.POST("Input your url", param.getBytes())
```

**Comment by yousung-ahn** [comment]
getBytes 였군요 해결하였습니다 감사합니다.
