### ISSUE TITLE
.war application doesn't contains org.ngrinder.common.util.SystemInfoUtils

### ISSUE THREAD

**Issue by kdw9502** [naver/ngrinder#709]
![image](https://user-images.githubusercontent.com/21076531/102852742-3f097400-4462-11eb-852e-2b7522818e5c.png)

org.ngrinder.common.util.SystemInfoUtils doesn't contained in war.

probably this cause #657 Validation issue

**Comment by imbyungjun** [comment]
`org.ngrinder.common.util.SystemInfoUtils` is located in `ngrinder-core` module.
