### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by yonger1516** [naver/ngrinder#71]
Hi,
the following dependencies missing while build with maven:

<dependency>
			<groupId>sigar</groupId>
			<artifactId>sigar-native</artifactId>
			<version>1.0</version>
		</dependency>

<dependency>
			<groupId>grinder</groupId>
			<artifactId>grinder-patch</artifactId>
			<version>3.9.1-patch</version>
		</dependency>
(actually,the dependency "grinder-patch" can be found in your naver repository, but mismatched group id and artifact id )

**Comment by junoyoon** [comment]
You should install the dependencies in advance... using
install_maven_lib.sh which can be found in  ngrinder project.

2015-07-16 17:17 GMT+09:00 yonger1516 <notifications@github.com>:

**Comment by yonger1516** [comment]
Thank you. it works. close the issue.
