### ISSUE TITLE
docker agent port option

### ISSUE THREAD

**Issue by k16wire** [naver/ngrinder#72]
Hi all.

Right not ngrinder agent docker image just get a controller web port and ip address as enviroment variable. This make a issue that controller need to have a same port as 16001. So we can't run only one controller at one docker host server.

If  we can specify controller live check port as enviroment variable in agent, it's possible to run one more controller at one server.

**Comment by junoyoon** [comment]
This is already possible to run multiple controllers using a single multi-ngrinder-controller image. 
See https://hub.docker.com/r/ngrinder/multi-controller/
