### ISSUE TITLE
performance test

### ISSUE THREAD

**Issue by zhengjy** [naver/ngrinder#725]
versiom 3.5.3

input  >0 message
![image](https://user-images.githubusercontent.com/12868597/103271698-e273ff00-49f5-11eb-96c1-8a132341d342.png)

input ==0 message

![image](https://user-images.githubusercontent.com/12868597/103271758-10594380-49f6-11eb-9b24-a4179be641d6.png)

What's wrong with the operation  Or the problem ?

**Comment by junoyoon** [comment]
You didn't attach any agent yet.

**Comment by junoyoon** [comment]
Please use discussion panel for question.
