### ISSUE TITLE
nGrinder downloadable CSV file format

### ISSUE THREAD

**Issue by thrax130** [naver/ngrinder#73]
All columns in the downloadable csv file are comma separated.
It would be nice to change this to semicolons. 
The issue occurs when you have floats as resulting values(in German floats have a comma instead of dot), so you can not distinct between columns and decimal places anymore.

I fixed it for my own but it may be interesting for someone else!

**Comment by junoyoon** [comment]
@songeunwoo  Could you change the separation with tab instead of comma?

**Comment by thrax130** [comment]
You can change this on your own in the source code.
If you need help to find the place in source code let me know, but all in all it is very easy😃

**Comment by songeunwoo** [comment]
After you have added the option of the config file csv.separator .
What give you change the value, depending on the option value.
Of course, the default value is comma.

**Comment by junoyoon** [comment]
Fixed..
