### ISSUE TITLE
Add checking es5 task to build cycle but, the es-check module has some problem

### ISSUE THREAD

**Issue by donggyu04** [naver/ngrinder#751]
I [added a task](https://github.com/naver/ngrinder/commit/bbdb67c941ba89ea029c7f5a818519c531ff189a) to our build cycle to check whether bundled javascript is es5 or not. but the [es-check](https://www.npmjs.com/package/es-check) module has some problems.
I think we have to find another module or fix the es-check.

#### 1. When pass build (no have es6 syntax)

```
> Task :ngrinder-frontend:checkES5
ES-Check: Going to check files using version 5
ES-Check: checking ../ngrinder-controller/build/classes/main/static/js/app.js
ES-Check: there were no ES version matching errors!  🎉

BUILD SUCCESSFUL in 50s
24 actionable tasks: 23 executed, 1 up-to-date
```

#### 2. When failed build (have es6 syntax)

```
> Task :ngrinder-frontend:checkES5
ES-Check: Going to check files using version 5
ES-Check: checking ../ngrinder-controller/build/classes/main/static/js/app.js
ES-Check: failed to parse file: ../ngrinder-controller/build/classes/main/static/js/app.js
 - error: SyntaxError: The keyword 'const' is reserved (102:144568)
ES-Check: there were 1 ES version matching errors.

          ES-Check Error:
          ----
          · erroring file: ../ngrinder-controller/build/classes/main/static/js/app.js
          · error: SyntaxError: The keyword 'const' is reserved (102:144568)
          · see the printed err.stack below for context
          ----

          SyntaxError: The keyword 'const' is reserved (102:144568)
    at Parser.pp$4.raise (/Users/user/.npm/_npx/55223/lib/node_modules/es-check/node_modules/acorn/dist/acorn.js:2825:15)
    
...

> Task :ngrinder-frontend:checkES5 FAILED

FAILURE: Build failed with an exception.

BUILD FAILED in 33s
21 actionable tasks: 18 executed, 3 up-to-date
```

## 2. es-check module issue

It does not catch some es6 keywords like `Object.assign, Promise`
Actually, When I test with the below script, es-check passes the task even if it has es6 syntax.

```
// es-check-testing.js

var myPromise = new Promise(function(resolve, reject) {
	resolve();
	reject();
});

var o1 = { a: 1 };
var o2 = { b: 2 };
var o3 = { c: 3 };

var obj = Object.assign(o1, o2, o3);
```

```
npx es-check es5 ./es-check-testing.js --verbose

ES-Check: Going to check files using version 5
ES-Check: checking ./es-check-testing.js
ES-Check: there were no ES version matching errors!  🎉
```

Relevant issues below.
https://github.com/dollarshaveclub/es-check/issues/122
https://github.com/dollarshaveclub/es-check/issues/72

**Comment by junoyoon** [comment]
As far as I understand ,es-check checks if it contains illegal syntax or not. ```Object.assign, Promise``` is not syntax but Identifier (which is provided by node).  ```Object.assign, Promise``` stuff should be handled by something else. However, embedding es-check is better to have, otherwise we may miss the syntax error stuff.
Just adopt es-check.

**Comment by donggyu04** [comment]
@junoyoon 

Yes, It can't completely check that the bundled code can run in IE, but I have [adopted it](https://github.com/naver/ngrinder/pull/754).
