### ISSUE TITLE
Starting process and use too much cpu resource.

### ISSUE THREAD

**Issue by kdw9502** [naver/ngrinder#757]
### 1. Describe the bug 🐞

 

Starting process, worker use too much cpu resource. Starting many processes sometime cause agent lost or other problems.

 

### 2. Reproduction steps

1. Make test with 10 process, set ramp up with 2 incremental step, Interval 10000ms

2. Run agent on windows 10

3. Run test

4. In Task Manager, CPU usage is 100% for every ramp up.

 

 

### 3. Environment

- Controller

     - OS: CentOs 3.10.0

     - Browser:

     - JDK version: openJDK jdk-15.0.1

     - Controller version: 3.5.3

- Agent

     - OS: Windows Server 2019

     - JDK version: openJDK jdk-15.0.1

     - Agent version: 3.5.3

 

### 4. Screenshots

![화면 캡처 2021-02-05 171245](https://user-images.githubusercontent.com/21076531/107008352-0685e580-67d7-11eb-8b18-8cd3f7afd2bf.png)

**Comment by donggyu04** [comment]
@kdw9502

In the process of preparing new workers for testing, you can use a lot of CPU momentarily.
Did you actually have some problem like agent loss or other?

**Comment by junoyoon** [comment]
1. How many CPU cores do you have?
2. Do your script do some job in @BeforeThread (sth like loading files?)

**Comment by kdw9502** [comment]
I found that some problems only occrus with python script test, not due to cpu usage
