### ISSUE TITLE
Script validation error

### ISSUE THREAD

**Issue by mashuangwei** [naver/ngrinder#848]
### 1. Describe the bug 🐞 
After the platform runs for one month, the verification script will report an error. In fact, if the script has no problem, you can only restart the platform and the verification script function can return to normal
 
Error message in script verification:
Error: Could not find or load main class net.grinder.engine.process.WorkerProcessEntryPoint

### 3. Environment
- Controller
     - OS: centos7
     - Browser:
     - JDK version: jdk8 
     - Controller version: 3.5.5
- Agent
     - OS: centos7
     - JDK version: jdk8 
     - Agent version:3.5.5

### 4. Screenshots
If necessary, add screenshots to help explain your problem.

**Comment by donggyu04** [comment]
@mashuangwei 

Could you restart controller?

**Comment by mashuangwei** [comment]
Yes, it's OK when I restart it, but there will be problems after running for one month. It can only be solved by restarting

**Comment by imbyungjun** [comment]
I reproduced the error. Also, it occured after running the ngrinder-controller about a month.

The ngrinder-controller log was like below
```
2022-08-24 16:23:03,097 INFO  LocalScriptTestDriveService.java:115 : 
grinder.jvm.classpath : /tmp/ngrinder.war-spring-boot-libs-061d2b83-cccb-4760-a0ad-abbd63b5cc3d/ngrinder-runtime-3.5.5-p2.jar
::/tmp/ngrinder.war-spring-boot-libs-061d2b83-cccb-4760-a0ad-abbd63b5cc3d/grinder-3.9.1-patch.jar
::/home/user/.ngrinder/script/admin
2022-08-24 16:23:03,099 INFO  LocalScriptTestDriveService.java:132 : jvm args :  -Djna.library.path=/home/user/.ngrinder/script/admin/lib  -Dpython.path=/home/user/.ngrinder/script/admin/lib  -Dpython.cachedir=/tmp/jython  -Dngrinder.etc.hosts=dev-fin-ngrinder-ctrl-001-ncl.nfra.io:127.0.0.1,localhost:127.0.0.1 -Dngrinder.enable.local-dns=true  -Duser.dir=/home/user/.ngrinder/script/admin  -Dngrinder.context=controller  -Dhttps.protocols=TLSv1.3,TLSv1.2,TLSv1.1,TLSv1,SSLv3  -Djsse.enableSNIExtension=false
2022-08-24 16:23:03,107 INFO  ErrorStreamRedirectWorkerLauncher.java:127 : worker validation-0 started
```

And the validation result was below.
```
Error: Could not find or load main class net.grinder.engine.process.WorkerProcessEntryPoint
```

It is an error on the worker process, not the controller side. So, this error can not be caught on the controller code. The controller starts worker process normally. However, the result of worker process is not the expected one.

I tried to find the library files that specified on jvm classpath. In my case, it was `/tmp/ngrinder.war-spring-boot-libs-061d2b83-cccb-4760-a0ad-abbd63b5cc3d/ngrinder-runtime-3.5.5-p2.jar` and `/tmp/ngrinder.war-spring-boot-libs-061d2b83-cccb-4760-a0ad-abbd63b5cc3d/grinder-3.9.1-patch.jar`.
When I check the `/tmp` directory, I could figure out why the error occurs after running the controller for a month.
There was no `/tmp/ngrinder.war-spring-boot-libs-061d2b83-cccb-4760-a0ad-abbd63b5cc3d` directory. The default period of cleaning up `/tmp` directory is 30 days. After 30 days, the library files for nGrinder in the `/tmp` directory cleaned up, then the worker process can not find libraries depends on.

This issue can be occurred when running ngrinder-controller directly with the `.war` file(without using Tomcat) for more than 30 days.
I'm gonna try to resolve this issue.

**Comment by donggyu04** [comment]
@imbyungjun 😨
