### ISSUE TITLE
한국어 메뉴얼 링크 깨짐

### ISSUE THREAD

**Issue by hojongs** [naver/ngrinder#880]
### 1. Describe the bug 🐞 
:exclamation: DO NOT ASK QUESTION HERE PLEASE USE [DISCUSSION](https://github.com/naver/ngrinder/discussions) INSTEAD.

https://github.com/naver/ngrinder/wiki/User-guide-in-Korean
위 페이지에 있는 4개 링크가 모두 존재하지 않는 페이지를 가리키고 있습니다.

각 link가 fix 혹은 제거되어야 할 것 같습니다

**Comment by imbyungjun** [comment]
Because of all the guide links are no more exists in the "User guide in Korean" page, I will remove the page. And will restore it again when there is another useful Korean guide.

---

한국어 메뉴얼이 있던 링크들이 모두 존재하지 않게되어서 더 이상 게시할 가이드가 없으므로 페이지를 제거하겠습니다. 후에 또 다른 유용한 한글 가이드가 있다면 다시 페이지를 만들겠습니다.
