### ISSUE TITLE
The script content is lost after verification

### ISSUE THREAD

**Issue by Nuoky** [naver/ngrinder#884]
### 1. Describe the bug 🐞 
If you continue to edit and use the validation function after saving, the script will return the last data.

### 2. Reproduction steps
1. Go to Script Editor
2. Enter any character and save
3. Enter any character and validate

### 3. Environment
- Controller
     - OS: Win10
     - Browser: Chrome
     - JDK version: 1.8
     - Controller version: 3.5.5 p1
- Agent
     - OS: Win10
     - JDK version: 1.8
     - Agent version: 3.5.5 p1

### 4. Screenshots
[Script-Editor.webm](https://user-images.githubusercontent.com/24731549/176886765-c407d364-a259-460c-aa9b-5cad343cec63.webm)

### 5. Solution
ngrinder-frontend\src\js\components\script\Editor.vue
```
editorSize = 70;
lastContent = ''
...
contentChanged() {
      // return !this.$utils.equalsIgnoreNewLineChar(this.$refs.editor.getValue(), this.file.content);
      return !this.$utils.equalsIgnoreNewLineChar(this.$refs.editor.getValue(), this.lastContent);
  }
...
// this.file.content = this.$refs.editor.getValue();
this.lastContent = this.$refs.editor.getValue();
```

**Comment by junoyoon** [comment]
Thx
I highly recommend u to make PR for it.
We will review and merge if it's OK.
