### ISSUE TITLE
java 1.8 error

### ISSUE THREAD

**Issue by chengaomin** [naver/ngrinder#91]
I hava some errors when I use java 1.8.
so I change java version to 1.7，it can run.
do you want to support java 1.8?

**Comment by GwonGisoo** [comment]
Java 1.8 is not support. but we preparing for the support.

**Comment by junoyoon** [comment]
Actually it was quite difficult job because underlying spring 3.X doesn't
support java 1.7.

However Last year, I've upgraded ngrinder spring version to 4.0 and have
the patch.  So it's a matter of time. We will merge it soon.

2016-03-16 10:58 GMT+09:00 권기수 <notifications@github.com>:

**Comment by svenkost** [comment]
I'd like to have the patch. I need to run ngrinder in java 8, so please upload it to another branch?

**Comment by junoyoon** [comment]
In my PC. :-(

**Comment by junoyoon** [comment]
jdk 1.8 support version is pushed in the master. U can now clone the master and make a package. using 

```./install_maven_lib.sh && mvn package -Dmaven.test.skip=true```
