### ISSUE TITLE
How to debug jython script in my PC?

### ISSUE THREAD

**Issue by chengaomin** [naver/ngrinder#93]
I used python in my work.
I don't know how to debug jython script in my pc offline.
I'll upload to svn when the script can run without errors.
eg：

from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest
from net.grinder.plugin.http import HTTPPluginControl
from HTTPClient import NVPair

control = HTTPPluginControl.getConnectionDefaults()

control.timeout = 6000

test1 = Test(1, "10.5.16.200")
request1 = HTTPRequest()

test1.record(request1)

class TestRunner:
	
	def __init__(self):
		grinder.statistics.delayReports=True
		pass

		
	def __call__(self):
		result = request1.GET("http://10.5.16.200:8009/static/cdtest/sc02.html")
		
		
		if result.getStatusCode() == 200 :
			grinder.statistics.forLastTest.success = 1
		elif result.getStatusCode() in (301, 302) :
			grinder.logger.warn("Warning. The response may not be correct. The response code was %d." %  result.getStatusCode()) 
			grinder.statistics.forLastTest.success = 1
		else :
			grinder.statistics.forLastTest.success = 0

This is the test script of nGrinder,I can not run it in my local PC.Can you Help me?

**Comment by junoyoon** [comment]
For jython, we don't support debugging feature, It's almost impossible due to lack of tool support.
