### ISSUE TITLE
why V3.5.7 Script Validation Error？

### ISSUE THREAD

**Issue by cwk0099** [naver/ngrinder#940]
os: amazon linux
How to run ngrinder：docker
Steps to reproduce the bug：always when click validate button

response in /script/api/validate
{
  "message" : "Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.ngrinder.common.util.SystemInfoUtils",
  "success" : false,
  "stackTrace" : "org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.ngrinder.common.util.SystemInfoUtils\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\n\tat org.ngrinder.security.PluggablePreAuthFilter.doFilter(PluggablePreAuthFilter.java:52)\n\tat org.ngrinder.infra.servlet.PluggableServletFilter.doFilter(PluggableServletFilter.java:61)\n\tat org.ngrinder.security.PluggablePreAuthFilter.doFilter(PluggablePreAuthFilter.java:52)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\nCaused by: java.lang.NoClassDefFoundError: Could not initialize class org.ngrinder.common.util.SystemInfoUtils\n\tat net.grinder.engine.agent.PropertyBuilder.buildJVMArgumentWithoutMemory(PropertyBuilder.java:208)\n\tat net.grinder.engine.agent.LocalScriptTestDriveService.doValidate(LocalScriptTestDriveService.java:131)\n\tat org.ngrinder.script.service.ScriptValidationService.validate(ScriptValidationService.java:117)\n\tat org.ngrinder.script.controller.FileEntryApiController.validate(FileEntryApiController.java:392)\n\t... 7 more\n"
}

**Comment by joonseolee** [comment]
I'm going to say me either. 
I run both of the controller and agent in the amazon linux docker.  
It didn't work after pushing the validate button in the script tab.  
fortunately, 3.5.5-p1 version is working now.  
I would like to keep an eye on this issue.

**Comment by AIMWLI** [comment]
docker 3.5.8 same

**Comment by TesterYu** [comment]
May I ask if this problem has been resolved

**Comment by imbyungjun** [comment]
Basically, this issue seems like a oshi error that is occurred in docker container env only.
After checking related codes, I found that there is no reason for the script validation function to depend on SystemInfoUtils. So, changed it not to access SystemInfoUtils in 3.5.9 release.
Actually, I could not reproduce this issue but, expect that NoClassDefFoundError does not occur anymore.
