### ISSUE TITLE
A typo in wiki - "scripting guide"

### ISSUE THREAD

**Issue by soongjamm** [naver/ngrinder#958]
### See [How to make each thread act differently](https://github.com/naver/ngrinder/wiki/How-to-make-each-thread-act-differently)

The description talks about "curNumber", but it is written as "threadId" in the example > beforeThread() 
![image](https://user-images.githubusercontent.com/23302253/221082421-4a086d21-c810-49fc-ad63-9387a3842832.png)

**Comment by donggyu04** [comment]
@soongjamm could you make a pull-request?

**Comment by soongjamm** [comment]
I think I don't have permission to access wiki, and can't make a PR for wiki page. 
or can I ?

**Comment by junoyoon** [comment]
Right.. @donggyu04 plz fix it

**Comment by donggyu04** [comment]
@soongjamm I fixed. thx for reporting

https://github.com/naver/ngrinder/wiki/How-to-make-each-thread-act-differently
