### ISSUE TITLE
Can't run Maven and Gradle By NGrinder Controller

### ISSUE THREAD

**Issue by binary-river** [naver/ngrinder#975]
### 1. Describe the bug 🐞 
Can't find Maven and Gradle when running NGrinder Controller even though maven_home and gradle_home are set already. 
( I think it happens only on windows. Reason will be described below )

It seems this problem caused by InstallationChecker.java file. ( ngrinder-controller/src/main/java/org/ngrinder/starter/InstallationChecker.java) 

first and second line of enum, there's command only "mvn -version", "gradle -version".
Unfortunately, on windows, that doens't work. Those only works on linux and might be mac.
On windows platform, that command should be changed to "mvn.cmd -version", "gradle.bat -version"

I hope it will help this project.

### 2. Reproduction steps
1. Go to directory Ngrinder controller war file exists.
2. run war file using java command "java -Djava.io.tmpdir=%NGRINDER_HOME%\lib -jar [warfilename].war
3. See error : 
"WARNING: Maven isn't installed, You can't run Maven groovy scripts. Please install Maven and set MAVEN_HOME."
"WARNING: Gradle isn't installed, You can't run Gradle groovy scripts. Please install Gradle and set GRADLE_HOME."

### 3. Environment
- Controller
     - OS: Windows NT
     - Browser: none
     - JDK version: 14
     - Controller version: 3.5.8

### 4. Screenshots
If necessary, add screenshots to help explain your problem.
![bug_report_ngrinder](https://github.com/naver/ngrinder/assets/66468384/2bfbc9c3-3c4d-45fc-ac63-4a08c47315bb)

**Comment by hlgaza** [comment]
I'm having a similar problem where ngrinder cannot find GRADLE_HOME, but in my installation `gradle -version` works fine.
![image](https://github.com/naver/ngrinder/assets/34805223/fb22bb64-3db1-4ba5-96f7-a57ada3576e7)
