### ISSUE TITLE
Unable to display target hosts data in detail report page.

### ISSUE THREAD

**Issue by MeYoung** [naver/ngrinder#98]
Use 3.4-SNAPSHOT war package. 
Unable to display target hosts data in detail report page.

**Comment by junoyoon** [comment]
@songeunwoo @GwonGisoo

**Comment by chengaomin** [comment]
I have the same issues.

/root/.ngrinder/perftest/0_999/30/report/monitor_system_10.5.22.130.data  has no data.

only one line `ip,system,collectTime,freeMemory,totalMemory,cpuUsedPercentage,receivedPerSec,sentPerSec,customValues`.

But it displayed the realtime data when it running test.

Target State
10.5.16.200 CPU-5.4% MEM-68% / RX-26.0K TX-7.4K

Use 3.4-SNAPSHOT

**Comment by chengaomin** [comment]
3.3 is ok
3.4 RC2 has this problem
3.4-SNAPSHOT has this problem

Please fix it,Thanks!

**Comment by junoyoon** [comment]
We're working on this. The fix will be included in 3.4 which will be
released by 2weeks.
2016. 4. 12. 오후 8:53에 "chengaomin" <notifications@github.com>님이 작성:

**Comment by junoyoon** [comment]
@chengaomin question.. Did u run the ngrinder-monitor in the target?

**Comment by chengaomin** [comment]
@junoyoon Yes,of course.

**Comment by chengaomin** [comment]
@junoyoon You havn't this problem?? 
Maybe the package has some errors by myself??
Can you share your package for me to test?

**Comment by junoyoon** [comment]
@chengaomin  We just didn't try to reproduce this problem yet. We're working on finalizing the other features and we(@songeunwoo)'ll work on this few days later.

**Comment by songeunwoo** [comment]
@chengaomin  @MeYoung 
We tested using 3.4-SNAPSHOT but we didn't find problem you had experienced.
did you download ngrinder monitor module and set it in your target server?
for reference... ngrinder is communicate using controller.monitor_port value in system.conf file.
Let me know after confirmation. thanks.

**Comment by junoyoon** [comment]
Fixed.

**Comment by MeYoung** [comment]
Thanks.
